// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class alias extends AST implements Located {

    public String name;
    public String asname;
    public int lineno;
    public int col_offset;
    public int end_lineno;
    public int end_col_offset;

    public alias(String name, String asname, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        this.name = name;
        this.asname = asname;
        this.lineno = lineno;
        this.col_offset = col_offset;
        this.end_lineno = end_lineno;
        this.end_col_offset = end_col_offset;
    }

    @Override
    public int lineno() {
        return lineno;
    }

    @Override
    public int col_offset() {
        return col_offset;
    }

    @Override
    public int end_lineno() {
        return end_lineno;
    }

    @Override
    public int end_col_offset() {
        return end_col_offset;
    }
}
