// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Assert extends stmt {

    public expr test;
    public expr msg;

    public Assert(expr test, expr msg, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.test = test;
        this.msg = msg;
    }

    @Override
    public Kind kind() {
        return Kind.Assert;
    }
}
