// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Assign extends stmt {

    public java.util.List<expr> targets;
    public expr value;
    public String type_comment;

    public Assign(java.util.List<expr> targets, expr value, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.targets = targets;
        this.value = value;
        this.type_comment = type_comment;
    }

    @Override
    public Kind kind() {
        return Kind.Assign;
    }
}
