// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

public enum cmpopType {
    Eq, NotEq, Lt, LtE, Gt, GtE, Is, IsNot, In, NotIn
}
