// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class ExceptHandler extends excepthandler {

    public expr type;
    public String name;
    public java.util.List<stmt> body;

    public ExceptHandler(expr type, String name, java.util.List<stmt> body, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.type = type;
        this.name = name;
        this.body = body;
    }

    @Override
    public Kind kind() {
        return Kind.ExceptHandler;
    }
}
