// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class GeneratorExp extends expr {

    public expr elt;
    public java.util.List<comprehension> generators;

    public GeneratorExp(expr elt, java.util.List<comprehension> generators, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.elt = elt;
        this.generators = generators;
    }

    @Override
    public Kind kind() {
        return Kind.GeneratorExp;
    }
}
