// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class If extends stmt {

    public expr test;
    public java.util.List<stmt> body;
    public java.util.List<stmt> orelse;

    public If(expr test, java.util.List<stmt> body, java.util.List<stmt> orelse, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.test = test;
        this.body = body;
        this.orelse = orelse;
    }

    @Override
    public Kind kind() {
        return Kind.If;
    }
}
