// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class ImportFrom extends stmt {

    public String module;
    public java.util.List<alias> names;
    public int level;
    public int is_lazy;

    public ImportFrom(String module, java.util.List<alias> names, int level, int is_lazy, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.module = module;
        this.names = names;
        this.level = level;
        this.is_lazy = is_lazy;
    }

    @Override
    public Kind kind() {
        return Kind.ImportFrom;
    }
}
