// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Lambda extends expr {

    public arguments args;
    public expr body;

    public Lambda(arguments args, expr body, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.args = args;
        this.body = body;
    }

    @Override
    public Kind kind() {
        return Kind.Lambda;
    }
}
