// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class match_case extends AST {

    public pattern pattern;
    public expr guard;
    public java.util.List<stmt> body;

    public match_case(pattern pattern, expr guard, java.util.List<stmt> body) {
        this.pattern = pattern;
        this.guard = guard;
        this.body = body;
    }
}
