// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class MatchClass extends pattern {

    public expr cls;
    public java.util.List<pattern> patterns;
    public java.util.List<String> kwd_attrs;
    public java.util.List<pattern> kwd_patterns;

    public MatchClass(expr cls, java.util.List<pattern> patterns, java.util.List<String> kwd_attrs, java.util.List<pattern> kwd_patterns, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.cls = cls;
        this.patterns = patterns;
        this.kwd_attrs = kwd_attrs;
        this.kwd_patterns = kwd_patterns;
    }

    @Override
    public Kind kind() {
        return Kind.MatchClass;
    }
}
