// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class TypeAlias extends stmt {

    public expr name;
    public java.util.List<type_param> type_params;
    public expr value;

    public TypeAlias(expr name, java.util.List<type_param> type_params, expr value, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.name = name;
        this.type_params = type_params;
        this.value = value;
    }

    @Override
    public Kind kind() {
        return Kind.TypeAlias;
    }
}
