// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class TypeVar extends type_param {

    public String name;
    public expr bound;
    public expr default_value;

    public TypeVar(String name, expr bound, expr default_value, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.name = name;
        this.bound = bound;
        this.default_value = default_value;
    }

    @Override
    public Kind kind() {
        return Kind.TypeVar;
    }
}
