// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class UnaryOp extends expr {

    public unaryopType op;
    public expr operand;

    public UnaryOp(unaryopType op, expr operand, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.op = op;
        this.operand = operand;
    }

    @Override
    public Kind kind() {
        return Kind.UnaryOp;
    }
}
