// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class With extends stmt {

    public java.util.List<withitem> items;
    public java.util.List<stmt> body;
    public String type_comment;

    public With(java.util.List<withitem> items, java.util.List<stmt> body, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.items = items;
        this.body = body;
        this.type_comment = type_comment;
    }

    @Override
    public Kind kind() {
        return Kind.With;
    }
}
