// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class AnnAssign extends stmt {

    public expr target;
    public expr annotation;
    public expr value;
    public int simple;

    public AnnAssign(expr target, expr annotation, expr value, int simple, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.target = target;
        this.annotation = annotation;
        this.value = value;
        this.simple = simple;
    }

    @Override
    public Kind kind() {
        return Kind.AnnAssign;
    }
}
