// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class arg extends AST implements Located {

    public String arg;
    public expr annotation;
    public String type_comment;
    public int lineno;
    public int col_offset;
    public int end_lineno;
    public int end_col_offset;

    public arg(String arg, expr annotation, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        this.arg = arg;
        this.annotation = annotation;
        this.type_comment = type_comment;
        this.lineno = lineno;
        this.col_offset = col_offset;
        this.end_lineno = end_lineno;
        this.end_col_offset = end_col_offset;
    }

    @Override
    public int lineno() {
        return lineno;
    }

    @Override
    public int col_offset() {
        return col_offset;
    }

    @Override
    public int end_lineno() {
        return end_lineno;
    }

    @Override
    public int end_col_offset() {
        return end_col_offset;
    }
}
