// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class arguments extends AST {

    public java.util.List<arg> posonlyargs;
    public java.util.List<arg> args;
    public arg vararg;
    public java.util.List<arg> kwonlyargs;
    public java.util.List<expr> kw_defaults;
    public arg kwarg;
    public java.util.List<expr> defaults;

    public arguments(java.util.List<arg> posonlyargs, java.util.List<arg> args, arg vararg, java.util.List<arg> kwonlyargs, java.util.List<expr> kw_defaults, arg kwarg, java.util.List<expr> defaults) {
        this.posonlyargs = posonlyargs;
        this.args = args;
        this.vararg = vararg;
        this.kwonlyargs = kwonlyargs;
        this.kw_defaults = kw_defaults;
        this.kwarg = kwarg;
        this.defaults = defaults;
    }
}
