// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Attribute extends expr {

    public expr value;
    public String attr;
    public expr_contextType ctx;

    public Attribute(expr value, String attr, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.value = value;
        this.attr = attr;
        this.ctx = ctx;
    }

    @Override
    public Kind kind() {
        return Kind.Attribute;
    }
}
