// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class AugAssign extends stmt {

    public expr target;
    public operatorType op;
    public expr value;

    public AugAssign(expr target, operatorType op, expr value, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.target = target;
        this.op = op;
        this.value = value;
    }

    @Override
    public Kind kind() {
        return Kind.AugAssign;
    }
}
