// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class BinOp extends expr {

    public expr left;
    public operatorType op;
    public expr right;

    public BinOp(expr left, operatorType op, expr right, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.left = left;
        this.op = op;
        this.right = right;
    }

    @Override
    public Kind kind() {
        return Kind.BinOp;
    }
}
