// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class BoolOp extends expr {

    public boolopType op;
    public java.util.List<expr> values;

    public BoolOp(boolopType op, java.util.List<expr> values, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.op = op;
        this.values = values;
    }

    @Override
    public Kind kind() {
        return Kind.BoolOp;
    }
}
