// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Call extends expr {

    public expr func;
    public java.util.List<expr> args;
    public java.util.List<keyword> keywords;

    public Call(expr func, java.util.List<expr> args, java.util.List<keyword> keywords, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.func = func;
        this.args = args;
        this.keywords = keywords;
    }

    @Override
    public Kind kind() {
        return Kind.Call;
    }
}
