// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class ClassDef extends stmt {

    public String name;
    public java.util.List<expr> bases;
    public java.util.List<keyword> keywords;
    public java.util.List<stmt> body;
    public java.util.List<expr> decorator_list;
    public java.util.List<type_param> type_params;

    public ClassDef(String name, java.util.List<expr> bases, java.util.List<keyword> keywords, java.util.List<stmt> body, java.util.List<expr> decorator_list, java.util.List<type_param> type_params, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.name = name;
        this.bases = bases;
        this.keywords = keywords;
        this.body = body;
        this.decorator_list = decorator_list;
        this.type_params = type_params;
    }

    @Override
    public Kind kind() {
        return Kind.ClassDef;
    }
}
