// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class comprehension extends AST {

    public expr target;
    public expr iter;
    public java.util.List<expr> ifs;
    public int is_async;

    public comprehension(expr target, expr iter, java.util.List<expr> ifs, int is_async) {
        this.target = target;
        this.iter = iter;
        this.ifs = ifs;
        this.is_async = is_async;
    }
}
