// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Compare extends expr {

    public expr left;
    public java.util.List<cmpopType> ops;
    public java.util.List<expr> comparators;

    public Compare(expr left, java.util.List<cmpopType> ops, java.util.List<expr> comparators, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.left = left;
        this.ops = ops;
        this.comparators = comparators;
    }

    @Override
    public Kind kind() {
        return Kind.Compare;
    }
}
