// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Delete extends stmt {

    public java.util.List<expr> targets;

    public Delete(java.util.List<expr> targets, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.targets = targets;
    }

    @Override
    public Kind kind() {
        return Kind.Delete;
    }
}
