// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Dict extends expr {

    public java.util.List<expr> keys;
    public java.util.List<expr> values;

    public Dict(java.util.List<expr> keys, java.util.List<expr> values, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.keys = keys;
        this.values = values;
    }

    @Override
    public Kind kind() {
        return Kind.Dict;
    }
}
