// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Expression extends mod {

    public expr body;

    public Expression(expr body) {
        this.body = body;
    }

    @Override
    public Kind kind() {
        return Kind.Expression;
    }
}
