// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class For extends stmt {

    public expr target;
    public expr iter;
    public java.util.List<stmt> body;
    public java.util.List<stmt> orelse;
    public String type_comment;

    public For(expr target, expr iter, java.util.List<stmt> body, java.util.List<stmt> orelse, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.target = target;
        this.iter = iter;
        this.body = body;
        this.orelse = orelse;
        this.type_comment = type_comment;
    }

    @Override
    public Kind kind() {
        return Kind.For;
    }
}
