// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class FormattedValue extends expr {

    public expr value;
    public int conversion;
    public expr format_spec;

    public FormattedValue(expr value, int conversion, expr format_spec, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.value = value;
        this.conversion = conversion;
        this.format_spec = format_spec;
    }

    @Override
    public Kind kind() {
        return Kind.FormattedValue;
    }
}
