// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class FunctionDef extends stmt {

    public String name;
    public arguments args;
    public java.util.List<stmt> body;
    public java.util.List<expr> decorator_list;
    public expr returns;
    public String type_comment;
    public java.util.List<type_param> type_params;

    public FunctionDef(String name, arguments args, java.util.List<stmt> body, java.util.List<expr> decorator_list, expr returns, String type_comment, java.util.List<type_param> type_params, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.name = name;
        this.args = args;
        this.body = body;
        this.decorator_list = decorator_list;
        this.returns = returns;
        this.type_comment = type_comment;
        this.type_params = type_params;
    }

    @Override
    public Kind kind() {
        return Kind.FunctionDef;
    }
}
