// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class FunctionType extends mod {

    public java.util.List<expr> argtypes;
    public expr returns;

    public FunctionType(java.util.List<expr> argtypes, expr returns) {
        this.argtypes = argtypes;
        this.returns = returns;
    }

    @Override
    public Kind kind() {
        return Kind.FunctionType;
    }
}
