// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class IfExp extends expr {

    public expr test;
    public expr body;
    public expr orelse;

    public IfExp(expr test, expr body, expr orelse, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.test = test;
        this.body = body;
        this.orelse = orelse;
    }

    @Override
    public Kind kind() {
        return Kind.IfExp;
    }
}
