// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class MatchSingleton extends pattern {

    public Object value;

    public MatchSingleton(Object value, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.value = value;
    }

    @Override
    public Kind kind() {
        return Kind.MatchSingleton;
    }
}
