// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class MatchMapping extends pattern {

    public java.util.List<expr> keys;
    public java.util.List<pattern> patterns;
    public String rest;

    public MatchMapping(java.util.List<expr> keys, java.util.List<pattern> patterns, String rest, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.keys = keys;
        this.patterns = patterns;
        this.rest = rest;
    }

    @Override
    public Kind kind() {
        return Kind.MatchMapping;
    }
}
