// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Match extends stmt {

    public expr subject;
    public java.util.List<match_case> cases;

    public Match(expr subject, java.util.List<match_case> cases, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.subject = subject;
        this.cases = cases;
    }

    @Override
    public Kind kind() {
        return Kind.Match;
    }
}
