// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Module extends mod {

    public java.util.List<stmt> body;
    public java.util.List<type_ignore> type_ignores;

    public Module(java.util.List<stmt> body, java.util.List<type_ignore> type_ignores) {
        this.body = body;
        this.type_ignores = type_ignores;
    }

    @Override
    public Kind kind() {
        return Kind.Module;
    }
}
