// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class Slice extends expr {

    public expr lower;
    public expr upper;
    public expr step;

    public Slice(expr lower, expr upper, expr step, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.lower = lower;
        this.upper = upper;
        this.step = step;
    }

    @Override
    public Kind kind() {
        return Kind.Slice;
    }
}
