// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class TryStar extends stmt {

    public java.util.List<stmt> body;
    public java.util.List<excepthandler> handlers;
    public java.util.List<stmt> orelse;
    public java.util.List<stmt> finalbody;

    public TryStar(java.util.List<stmt> body, java.util.List<excepthandler> handlers, java.util.List<stmt> orelse, java.util.List<stmt> finalbody, int lineno, int col_offset, int end_lineno, int end_col_offset) {
        super(lineno, col_offset, end_lineno, end_col_offset);
        this.body = body;
        this.handlers = handlers;
        this.orelse = orelse;
        this.finalbody = finalbody;
    }

    @Override
    public Kind kind() {
        return Kind.TryStar;
    }
}
