// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class TypeIgnore extends type_ignore {

    public int lineno;
    public String tag;

    public TypeIgnore(int lineno, String tag) {
        this.lineno = lineno;
        this.tag = tag;
    }

    @Override
    public Kind kind() {
        return Kind.TypeIgnore;
    }
}
