// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

public enum unaryopType {
    Invert, Not, UAdd, USub
}
