// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast;

import org.python.pegen.ast.base.*;

public final class withitem extends AST {

    public expr context_expr;
    public expr optional_vars;

    public withitem(expr context_expr, expr optional_vars) {
        this.context_expr = context_expr;
        this.optional_vars = optional_vars;
    }
}
