// @generated by src/pegen/tools/generate_opcodes.py from CPython 3.15.0rc2
// DO NOT EDIT. Regenerate with src/pegen/tools/generate_opcodes.py
package org.python.pegen.compile;

/**
 * CPython's opcodes (Include/opcode_ids.h, pseudo-instructions included) and
 * the parts of pycore_opcode_metadata.h, pycore_intrinsics.h and
 * pycore_ceval.h the compiler uses.
 */
public final class Opcode {
    private Opcode() {}

    public static final int CACHE = 0;
    public static final int BINARY_SLICE = 1;
    public static final int BUILD_TEMPLATE = 2;
    public static final int CALL_FUNCTION_EX = 4;
    public static final int CHECK_EG_MATCH = 5;
    public static final int CHECK_EXC_MATCH = 6;
    public static final int CLEANUP_THROW = 7;
    public static final int DELETE_SUBSCR = 8;
    public static final int END_FOR = 9;
    public static final int END_SEND = 10;
    public static final int EXIT_INIT_CHECK = 11;
    public static final int FORMAT_SIMPLE = 12;
    public static final int FORMAT_WITH_SPEC = 13;
    public static final int GET_AITER = 14;
    public static final int GET_ANEXT = 15;
    public static final int GET_LEN = 16;
    public static final int RESERVED = 17;
    public static final int INTERPRETER_EXIT = 18;
    public static final int LOAD_BUILD_CLASS = 19;
    public static final int LOAD_LOCALS = 20;
    public static final int MAKE_FUNCTION = 21;
    public static final int MATCH_KEYS = 22;
    public static final int MATCH_MAPPING = 23;
    public static final int MATCH_SEQUENCE = 24;
    public static final int NOP = 25;
    public static final int NOT_TAKEN = 26;
    public static final int POP_EXCEPT = 27;
    public static final int POP_ITER = 28;
    public static final int POP_TOP = 29;
    public static final int PUSH_EXC_INFO = 30;
    public static final int PUSH_NULL = 31;
    public static final int RETURN_GENERATOR = 32;
    public static final int RETURN_VALUE = 33;
    public static final int SETUP_ANNOTATIONS = 34;
    public static final int STORE_SLICE = 35;
    public static final int STORE_SUBSCR = 36;
    public static final int TO_BOOL = 37;
    public static final int UNARY_INVERT = 38;
    public static final int UNARY_NEGATIVE = 39;
    public static final int UNARY_NOT = 40;
    public static final int WITH_EXCEPT_START = 41;
    public static final int BINARY_OP = 42;
    public static final int BUILD_INTERPOLATION = 43;
    public static final int BUILD_LIST = 44;
    public static final int BUILD_MAP = 45;
    public static final int BUILD_SET = 46;
    public static final int BUILD_SLICE = 47;
    public static final int BUILD_STRING = 48;
    public static final int BUILD_TUPLE = 49;
    public static final int CALL = 50;
    public static final int CALL_INTRINSIC_1 = 51;
    public static final int CALL_INTRINSIC_2 = 52;
    public static final int CALL_KW = 53;
    public static final int COMPARE_OP = 54;
    public static final int CONTAINS_OP = 55;
    public static final int CONVERT_VALUE = 56;
    public static final int COPY = 57;
    public static final int COPY_FREE_VARS = 58;
    public static final int DELETE_ATTR = 59;
    public static final int DELETE_DEREF = 60;
    public static final int DELETE_FAST = 61;
    public static final int DELETE_GLOBAL = 62;
    public static final int DELETE_NAME = 63;
    public static final int DICT_MERGE = 64;
    public static final int DICT_UPDATE = 65;
    public static final int END_ASYNC_FOR = 66;
    public static final int EXTENDED_ARG = 67;
    public static final int FOR_ITER = 68;
    public static final int GET_AWAITABLE = 69;
    public static final int GET_ITER = 70;
    public static final int IMPORT_FROM = 71;
    public static final int IMPORT_NAME = 72;
    public static final int IS_OP = 73;
    public static final int JUMP_BACKWARD = 74;
    public static final int JUMP_BACKWARD_NO_INTERRUPT = 75;
    public static final int JUMP_FORWARD = 76;
    public static final int LIST_APPEND = 77;
    public static final int LIST_EXTEND = 78;
    public static final int LOAD_ATTR = 79;
    public static final int LOAD_COMMON_CONSTANT = 80;
    public static final int LOAD_CONST = 81;
    public static final int LOAD_DEREF = 82;
    public static final int LOAD_FAST = 83;
    public static final int LOAD_FAST_AND_CLEAR = 84;
    public static final int LOAD_FAST_BORROW = 85;
    public static final int LOAD_FAST_BORROW_LOAD_FAST_BORROW = 86;
    public static final int LOAD_FAST_CHECK = 87;
    public static final int LOAD_FAST_LOAD_FAST = 88;
    public static final int LOAD_FROM_DICT_OR_DEREF = 89;
    public static final int LOAD_FROM_DICT_OR_GLOBALS = 90;
    public static final int LOAD_GLOBAL = 91;
    public static final int LOAD_NAME = 92;
    public static final int LOAD_SMALL_INT = 93;
    public static final int LOAD_SPECIAL = 94;
    public static final int LOAD_SUPER_ATTR = 95;
    public static final int MAKE_CELL = 96;
    public static final int MAP_ADD = 97;
    public static final int MATCH_CLASS = 98;
    public static final int POP_JUMP_IF_FALSE = 99;
    public static final int POP_JUMP_IF_NONE = 100;
    public static final int POP_JUMP_IF_NOT_NONE = 101;
    public static final int POP_JUMP_IF_TRUE = 102;
    public static final int RAISE_VARARGS = 103;
    public static final int RERAISE = 104;
    public static final int SEND = 105;
    public static final int SET_ADD = 106;
    public static final int SET_FUNCTION_ATTRIBUTE = 107;
    public static final int SET_UPDATE = 108;
    public static final int STORE_ATTR = 109;
    public static final int STORE_DEREF = 110;
    public static final int STORE_FAST = 111;
    public static final int STORE_FAST_LOAD_FAST = 112;
    public static final int STORE_FAST_STORE_FAST = 113;
    public static final int STORE_GLOBAL = 114;
    public static final int STORE_NAME = 115;
    public static final int SWAP = 116;
    public static final int UNPACK_EX = 117;
    public static final int UNPACK_SEQUENCE = 118;
    public static final int YIELD_VALUE = 119;
    public static final int RESUME = 128;
    public static final int INSTRUMENTED_END_FOR = 233;
    public static final int INSTRUMENTED_POP_ITER = 234;
    public static final int INSTRUMENTED_END_SEND = 235;
    public static final int INSTRUMENTED_FOR_ITER = 236;
    public static final int INSTRUMENTED_INSTRUCTION = 237;
    public static final int INSTRUMENTED_JUMP_FORWARD = 238;
    public static final int INSTRUMENTED_NOT_TAKEN = 239;
    public static final int INSTRUMENTED_POP_JUMP_IF_TRUE = 240;
    public static final int INSTRUMENTED_POP_JUMP_IF_FALSE = 241;
    public static final int INSTRUMENTED_POP_JUMP_IF_NONE = 242;
    public static final int INSTRUMENTED_POP_JUMP_IF_NOT_NONE = 243;
    public static final int INSTRUMENTED_RESUME = 244;
    public static final int INSTRUMENTED_RETURN_VALUE = 245;
    public static final int INSTRUMENTED_YIELD_VALUE = 246;
    public static final int INSTRUMENTED_END_ASYNC_FOR = 247;
    public static final int INSTRUMENTED_LOAD_SUPER_ATTR = 248;
    public static final int INSTRUMENTED_CALL = 249;
    public static final int INSTRUMENTED_CALL_KW = 250;
    public static final int INSTRUMENTED_CALL_FUNCTION_EX = 251;
    public static final int INSTRUMENTED_JUMP_BACKWARD = 252;
    public static final int INSTRUMENTED_LINE = 253;
    public static final int ENTER_EXECUTOR = 254;
    public static final int TRACE_RECORD = 255;
    public static final int ANNOTATIONS_PLACEHOLDER = 256;
    public static final int JUMP = 257;
    public static final int JUMP_IF_FALSE = 258;
    public static final int JUMP_IF_TRUE = 259;
    public static final int JUMP_NO_INTERRUPT = 260;
    public static final int LOAD_CLOSURE = 261;
    public static final int POP_BLOCK = 262;
    public static final int SETUP_CLEANUP = 263;
    public static final int SETUP_FINALLY = 264;
    public static final int SETUP_WITH = 265;
    public static final int STORE_FAST_MAYBE_NULL = 266;

    /** One past the largest opcode. */
    public static final int MAX_OPCODE_PLUS_ONE = 267;

    /** Opcode names, by opcode (null where there is none). */
    public static final String[] OPNAME = {
        "CACHE",
        "BINARY_SLICE",
        "BUILD_TEMPLATE",
        null,
        "CALL_FUNCTION_EX",
        "CHECK_EG_MATCH",
        "CHECK_EXC_MATCH",
        "CLEANUP_THROW",
        "DELETE_SUBSCR",
        "END_FOR",
        "END_SEND",
        "EXIT_INIT_CHECK",
        "FORMAT_SIMPLE",
        "FORMAT_WITH_SPEC",
        "GET_AITER",
        "GET_ANEXT",
        "GET_LEN",
        "RESERVED",
        "INTERPRETER_EXIT",
        "LOAD_BUILD_CLASS",
        "LOAD_LOCALS",
        "MAKE_FUNCTION",
        "MATCH_KEYS",
        "MATCH_MAPPING",
        "MATCH_SEQUENCE",
        "NOP",
        "NOT_TAKEN",
        "POP_EXCEPT",
        "POP_ITER",
        "POP_TOP",
        "PUSH_EXC_INFO",
        "PUSH_NULL",
        "RETURN_GENERATOR",
        "RETURN_VALUE",
        "SETUP_ANNOTATIONS",
        "STORE_SLICE",
        "STORE_SUBSCR",
        "TO_BOOL",
        "UNARY_INVERT",
        "UNARY_NEGATIVE",
        "UNARY_NOT",
        "WITH_EXCEPT_START",
        "BINARY_OP",
        "BUILD_INTERPOLATION",
        "BUILD_LIST",
        "BUILD_MAP",
        "BUILD_SET",
        "BUILD_SLICE",
        "BUILD_STRING",
        "BUILD_TUPLE",
        "CALL",
        "CALL_INTRINSIC_1",
        "CALL_INTRINSIC_2",
        "CALL_KW",
        "COMPARE_OP",
        "CONTAINS_OP",
        "CONVERT_VALUE",
        "COPY",
        "COPY_FREE_VARS",
        "DELETE_ATTR",
        "DELETE_DEREF",
        "DELETE_FAST",
        "DELETE_GLOBAL",
        "DELETE_NAME",
        "DICT_MERGE",
        "DICT_UPDATE",
        "END_ASYNC_FOR",
        "EXTENDED_ARG",
        "FOR_ITER",
        "GET_AWAITABLE",
        "GET_ITER",
        "IMPORT_FROM",
        "IMPORT_NAME",
        "IS_OP",
        "JUMP_BACKWARD",
        "JUMP_BACKWARD_NO_INTERRUPT",
        "JUMP_FORWARD",
        "LIST_APPEND",
        "LIST_EXTEND",
        "LOAD_ATTR",
        "LOAD_COMMON_CONSTANT",
        "LOAD_CONST",
        "LOAD_DEREF",
        "LOAD_FAST",
        "LOAD_FAST_AND_CLEAR",
        "LOAD_FAST_BORROW",
        "LOAD_FAST_BORROW_LOAD_FAST_BORROW",
        "LOAD_FAST_CHECK",
        "LOAD_FAST_LOAD_FAST",
        "LOAD_FROM_DICT_OR_DEREF",
        "LOAD_FROM_DICT_OR_GLOBALS",
        "LOAD_GLOBAL",
        "LOAD_NAME",
        "LOAD_SMALL_INT",
        "LOAD_SPECIAL",
        "LOAD_SUPER_ATTR",
        "MAKE_CELL",
        "MAP_ADD",
        "MATCH_CLASS",
        "POP_JUMP_IF_FALSE",
        "POP_JUMP_IF_NONE",
        "POP_JUMP_IF_NOT_NONE",
        "POP_JUMP_IF_TRUE",
        "RAISE_VARARGS",
        "RERAISE",
        "SEND",
        "SET_ADD",
        "SET_FUNCTION_ATTRIBUTE",
        "SET_UPDATE",
        "STORE_ATTR",
        "STORE_DEREF",
        "STORE_FAST",
        "STORE_FAST_LOAD_FAST",
        "STORE_FAST_STORE_FAST",
        "STORE_GLOBAL",
        "STORE_NAME",
        "SWAP",
        "UNPACK_EX",
        "UNPACK_SEQUENCE",
        "YIELD_VALUE",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "RESUME",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "INSTRUMENTED_END_FOR",
        "INSTRUMENTED_POP_ITER",
        "INSTRUMENTED_END_SEND",
        "INSTRUMENTED_FOR_ITER",
        "INSTRUMENTED_INSTRUCTION",
        "INSTRUMENTED_JUMP_FORWARD",
        "INSTRUMENTED_NOT_TAKEN",
        "INSTRUMENTED_POP_JUMP_IF_TRUE",
        "INSTRUMENTED_POP_JUMP_IF_FALSE",
        "INSTRUMENTED_POP_JUMP_IF_NONE",
        "INSTRUMENTED_POP_JUMP_IF_NOT_NONE",
        "INSTRUMENTED_RESUME",
        "INSTRUMENTED_RETURN_VALUE",
        "INSTRUMENTED_YIELD_VALUE",
        "INSTRUMENTED_END_ASYNC_FOR",
        "INSTRUMENTED_LOAD_SUPER_ATTR",
        "INSTRUMENTED_CALL",
        "INSTRUMENTED_CALL_KW",
        "INSTRUMENTED_CALL_FUNCTION_EX",
        "INSTRUMENTED_JUMP_BACKWARD",
        "INSTRUMENTED_LINE",
        "ENTER_EXECUTOR",
        "TRACE_RECORD",
        "ANNOTATIONS_PLACEHOLDER",
        "JUMP",
        "JUMP_IF_FALSE",
        "JUMP_IF_TRUE",
        "JUMP_NO_INTERRUPT",
        "LOAD_CLOSURE",
        "POP_BLOCK",
        "SETUP_CLEANUP",
        "SETUP_FINALLY",
        "SETUP_WITH",
        "STORE_FAST_MAYBE_NULL",
    };

    private static final int HAS_ARG_FLAG = 1;
    private static final int HAS_CONST_FLAG = 2;
    private static final int HAS_NAME_FLAG = 4;
    private static final int HAS_JUMP_FLAG = 8;
    private static final int HAS_FREE_FLAG = 16;
    private static final int HAS_LOCAL_FLAG = 32;
    private static final int HAS_EXC_FLAG = 64;

    private static final int[] FLAGS = new int[MAX_OPCODE_PLUS_ONE];
    static {
        FLAGS[BINARY_OP] = HAS_ARG_FLAG;
        FLAGS[BUILD_INTERPOLATION] = HAS_ARG_FLAG;
        FLAGS[BUILD_LIST] = HAS_ARG_FLAG;
        FLAGS[BUILD_MAP] = HAS_ARG_FLAG;
        FLAGS[BUILD_SET] = HAS_ARG_FLAG;
        FLAGS[BUILD_SLICE] = HAS_ARG_FLAG;
        FLAGS[BUILD_STRING] = HAS_ARG_FLAG;
        FLAGS[BUILD_TUPLE] = HAS_ARG_FLAG;
        FLAGS[CALL] = HAS_ARG_FLAG;
        FLAGS[CALL_INTRINSIC_1] = HAS_ARG_FLAG;
        FLAGS[CALL_INTRINSIC_2] = HAS_ARG_FLAG;
        FLAGS[CALL_KW] = HAS_ARG_FLAG;
        FLAGS[COMPARE_OP] = HAS_ARG_FLAG;
        FLAGS[CONTAINS_OP] = HAS_ARG_FLAG;
        FLAGS[CONVERT_VALUE] = HAS_ARG_FLAG;
        FLAGS[COPY] = HAS_ARG_FLAG;
        FLAGS[COPY_FREE_VARS] = HAS_ARG_FLAG;
        FLAGS[DELETE_ATTR] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[DELETE_DEREF] = HAS_ARG_FLAG | HAS_FREE_FLAG;
        FLAGS[DELETE_FAST] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[DELETE_GLOBAL] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[DELETE_NAME] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[DICT_MERGE] = HAS_ARG_FLAG;
        FLAGS[DICT_UPDATE] = HAS_ARG_FLAG;
        FLAGS[END_ASYNC_FOR] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[EXTENDED_ARG] = HAS_ARG_FLAG;
        FLAGS[FOR_ITER] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[GET_AWAITABLE] = HAS_ARG_FLAG;
        FLAGS[GET_ITER] = HAS_ARG_FLAG;
        FLAGS[IMPORT_FROM] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[IMPORT_NAME] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[IS_OP] = HAS_ARG_FLAG;
        FLAGS[JUMP_BACKWARD] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[JUMP_BACKWARD_NO_INTERRUPT] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[JUMP_FORWARD] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[LIST_APPEND] = HAS_ARG_FLAG;
        FLAGS[LIST_EXTEND] = HAS_ARG_FLAG;
        FLAGS[LOAD_ATTR] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[LOAD_COMMON_CONSTANT] = HAS_ARG_FLAG;
        FLAGS[LOAD_CONST] = HAS_ARG_FLAG | HAS_CONST_FLAG;
        FLAGS[LOAD_DEREF] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FAST] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FAST_AND_CLEAR] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FAST_BORROW] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FAST_BORROW_LOAD_FAST_BORROW] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FAST_CHECK] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FAST_LOAD_FAST] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[LOAD_FROM_DICT_OR_DEREF] = HAS_ARG_FLAG | HAS_FREE_FLAG;
        FLAGS[LOAD_FROM_DICT_OR_GLOBALS] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[LOAD_GLOBAL] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[LOAD_NAME] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[LOAD_SMALL_INT] = HAS_ARG_FLAG;
        FLAGS[LOAD_SPECIAL] = HAS_ARG_FLAG;
        FLAGS[LOAD_SUPER_ATTR] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[MAKE_CELL] = HAS_ARG_FLAG | HAS_FREE_FLAG;
        FLAGS[MAP_ADD] = HAS_ARG_FLAG;
        FLAGS[MATCH_CLASS] = HAS_ARG_FLAG;
        FLAGS[POP_JUMP_IF_FALSE] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[POP_JUMP_IF_NONE] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[POP_JUMP_IF_NOT_NONE] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[POP_JUMP_IF_TRUE] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[RAISE_VARARGS] = HAS_ARG_FLAG;
        FLAGS[RERAISE] = HAS_ARG_FLAG;
        FLAGS[SEND] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[SET_ADD] = HAS_ARG_FLAG;
        FLAGS[SET_FUNCTION_ATTRIBUTE] = HAS_ARG_FLAG;
        FLAGS[SET_UPDATE] = HAS_ARG_FLAG;
        FLAGS[STORE_ATTR] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[STORE_DEREF] = HAS_ARG_FLAG | HAS_FREE_FLAG;
        FLAGS[STORE_FAST] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[STORE_FAST_LOAD_FAST] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[STORE_FAST_STORE_FAST] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[STORE_GLOBAL] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[STORE_NAME] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[SWAP] = HAS_ARG_FLAG;
        FLAGS[UNPACK_EX] = HAS_ARG_FLAG;
        FLAGS[UNPACK_SEQUENCE] = HAS_ARG_FLAG;
        FLAGS[YIELD_VALUE] = HAS_ARG_FLAG;
        FLAGS[RESUME] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_FOR_ITER] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[INSTRUMENTED_JUMP_FORWARD] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_POP_JUMP_IF_TRUE] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_POP_JUMP_IF_FALSE] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_POP_JUMP_IF_NONE] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_POP_JUMP_IF_NOT_NONE] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_RESUME] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_YIELD_VALUE] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_END_ASYNC_FOR] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[INSTRUMENTED_LOAD_SUPER_ATTR] = HAS_ARG_FLAG | HAS_NAME_FLAG;
        FLAGS[INSTRUMENTED_CALL] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_CALL_KW] = HAS_ARG_FLAG;
        FLAGS[INSTRUMENTED_JUMP_BACKWARD] = HAS_ARG_FLAG;
        FLAGS[ENTER_EXECUTOR] = HAS_ARG_FLAG;
        FLAGS[TRACE_RECORD] = HAS_ARG_FLAG;
        FLAGS[JUMP] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[JUMP_IF_FALSE] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[JUMP_IF_TRUE] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[JUMP_NO_INTERRUPT] = HAS_ARG_FLAG | HAS_JUMP_FLAG;
        FLAGS[LOAD_CLOSURE] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
        FLAGS[SETUP_CLEANUP] = HAS_ARG_FLAG | HAS_EXC_FLAG;
        FLAGS[SETUP_FINALLY] = HAS_ARG_FLAG | HAS_EXC_FLAG;
        FLAGS[SETUP_WITH] = HAS_ARG_FLAG | HAS_EXC_FLAG;
        FLAGS[STORE_FAST_MAYBE_NULL] = HAS_ARG_FLAG | HAS_LOCAL_FLAG;
    }

    /** C: OPCODE_HAS_ARG(op). */
    public static boolean OPCODE_HAS_ARG(int op) {
        return (FLAGS[op] & HAS_ARG_FLAG) != 0;
    }

    /** C: OPCODE_HAS_CONST(op). */
    public static boolean OPCODE_HAS_CONST(int op) {
        return (FLAGS[op] & HAS_CONST_FLAG) != 0;
    }

    /** C: OPCODE_HAS_NAME(op). */
    public static boolean OPCODE_HAS_NAME(int op) {
        return (FLAGS[op] & HAS_NAME_FLAG) != 0;
    }

    /** C: OPCODE_HAS_JUMP(op). */
    public static boolean OPCODE_HAS_JUMP(int op) {
        return (FLAGS[op] & HAS_JUMP_FLAG) != 0;
    }

    /** C: OPCODE_HAS_FREE(op). */
    public static boolean OPCODE_HAS_FREE(int op) {
        return (FLAGS[op] & HAS_FREE_FLAG) != 0;
    }

    /** C: OPCODE_HAS_LOCAL(op). */
    public static boolean OPCODE_HAS_LOCAL(int op) {
        return (FLAGS[op] & HAS_LOCAL_FLAG) != 0;
    }

    /** C: OPCODE_HAS_EXC(op). */
    public static boolean OPCODE_HAS_EXC(int op) {
        return (FLAGS[op] & HAS_EXC_FLAG) != 0;
    }

    /* BINARY_OP operands (Include/internal/pycore_code.h NB_*) */
    public static final int NB_ADD = 0;
    public static final int NB_AND = 1;
    public static final int NB_FLOOR_DIVIDE = 2;
    public static final int NB_LSHIFT = 3;
    public static final int NB_MATRIX_MULTIPLY = 4;
    public static final int NB_MULTIPLY = 5;
    public static final int NB_REMAINDER = 6;
    public static final int NB_OR = 7;
    public static final int NB_POWER = 8;
    public static final int NB_RSHIFT = 9;
    public static final int NB_SUBTRACT = 10;
    public static final int NB_TRUE_DIVIDE = 11;
    public static final int NB_XOR = 12;
    public static final int NB_INPLACE_ADD = 13;
    public static final int NB_INPLACE_AND = 14;
    public static final int NB_INPLACE_FLOOR_DIVIDE = 15;
    public static final int NB_INPLACE_LSHIFT = 16;
    public static final int NB_INPLACE_MATRIX_MULTIPLY = 17;
    public static final int NB_INPLACE_MULTIPLY = 18;
    public static final int NB_INPLACE_REMAINDER = 19;
    public static final int NB_INPLACE_OR = 20;
    public static final int NB_INPLACE_POWER = 21;
    public static final int NB_INPLACE_RSHIFT = 22;
    public static final int NB_INPLACE_SUBTRACT = 23;
    public static final int NB_INPLACE_TRUE_DIVIDE = 24;
    public static final int NB_INPLACE_XOR = 25;
    public static final int NB_SUBSCR = 26;

    /* CALL_INTRINSIC_1 operands (Include/internal/pycore_intrinsics.h) */
    public static final int INTRINSIC_1_INVALID = 0;
    public static final int INTRINSIC_PRINT = 1;
    public static final int INTRINSIC_IMPORT_STAR = 2;
    public static final int INTRINSIC_STOPITERATION_ERROR = 3;
    public static final int INTRINSIC_ASYNC_GEN_WRAP = 4;
    public static final int INTRINSIC_UNARY_POSITIVE = 5;
    public static final int INTRINSIC_LIST_TO_TUPLE = 6;
    public static final int INTRINSIC_TYPEVAR = 7;
    public static final int INTRINSIC_PARAMSPEC = 8;
    public static final int INTRINSIC_TYPEVARTUPLE = 9;
    public static final int INTRINSIC_SUBSCRIPT_GENERIC = 10;
    public static final int INTRINSIC_TYPEALIAS = 11;

    /* CALL_INTRINSIC_2 operands */
    public static final int INTRINSIC_2_INVALID = 0;
    public static final int INTRINSIC_PREP_RERAISE_STAR = 1;
    public static final int INTRINSIC_TYPEVAR_WITH_BOUND = 2;
    public static final int INTRINSIC_TYPEVAR_WITH_CONSTRAINTS = 3;
    public static final int INTRINSIC_SET_FUNCTION_TYPE_PARAMS = 4;
    public static final int INTRINSIC_SET_TYPEPARAM_DEFAULT = 5;

    /* LOAD_SPECIAL operands (Include/internal/pycore_ceval.h SPECIAL_*) */
    public static final int SPECIAL___ENTER__ = 0;
    public static final int SPECIAL___EXIT__ = 1;
    public static final int SPECIAL___AENTER__ = 2;
    public static final int SPECIAL___AEXIT__ = 3;
}
