// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast.base;

import org.python.pegen.ast.AST;
import org.python.pegen.ast.Located;

public abstract class excepthandler extends AST implements Located {

    public enum Kind {
        ExceptHandler
    }

    public int lineno;
    public int col_offset;
    public int end_lineno;
    public int end_col_offset;

    protected excepthandler(int lineno, int col_offset, int end_lineno, int end_col_offset) {
        this.lineno = lineno;
        this.col_offset = col_offset;
        this.end_lineno = end_lineno;
        this.end_col_offset = end_col_offset;
    }

    public abstract Kind kind();

    @Override
    public int lineno() {
        return lineno;
    }

    @Override
    public int col_offset() {
        return col_offset;
    }

    @Override
    public int end_lineno() {
        return end_lineno;
    }

    @Override
    public int end_col_offset() {
        return end_col_offset;
    }
}
