// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast.base;

import org.python.pegen.ast.AST;
import org.python.pegen.ast.Located;

public abstract class mod extends AST {

    public enum Kind {
        Module, Interactive, Expression, FunctionType
    }

    public abstract Kind kind();
}
