// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen.ast.base;

import org.python.pegen.ast.AST;
import org.python.pegen.ast.Located;

public abstract class type_ignore extends AST {

    public enum Kind {
        TypeIgnore
    }

    public abstract Kind kind();
}
