"""Generate the Python 3 AST classes and AstFactory from Parser/Python.asdl.

The Java counterpart of CPython's Parser/asdl_c.py; parsing of the ASDL file
is done by CPython's own Parser/asdl.py (imported from the CPython checkout,
as generate.py imports pegen).

Output, into the org.python.pegen.ast package directory:
  - one class per constructor (BinOp, Name, ...) and per product type
    (arguments, keyword, ...), with public fields named as in the ASDL;
  - one enum per simple sum, named with a Type suffix (expr_contextType,
    operatorType, ...);
  - in the base subpackage, one abstract class per sum type (expr, stmt, ...)
    holding the sum's attributes (lineno, col_offset, ...), a Kind enum and
    kind(), so ports of `switch (e->kind)` read like the C.
The subpackage and the suffix follow Jython 2.7's generated AST
(org.python.antlr.base.expr, boolopType): ASDL has names differing only in
case (expr/Expr, boolop/BoolOp), which cannot share a directory on
case-insensitive file systems.
And, into the org.python.pegen package directory, AstFactory.java: the
_PyAST_* constructor functions of Python/Python-ast.c with their C
signatures, including the same required-field checks.

Type mapping: identifier and string -> String; constant -> Object (see
org.python.pegen.ast for the value classes); int -> int; T* ->
java.util.List<T>, always written fully qualified because the AST has its
own List node.
"""

import os

HEADER = """\
// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
"""

AST_PACKAGE = "org.python.pegen.ast"
BASE_PACKAGE = AST_PACKAGE + ".base"
AST_IMPORTS = f"import {BASE_PACKAGE}.*;\n\n"
LOCATION = ["lineno", "col_offset", "end_lineno", "end_col_offset"]
BUILTIN = {"identifier": "String", "string": "String", "constant": "Object", "int": "int"}


class AsdlJavaGenerator:
    def __init__(self, asdl_module):
        self.mod = asdl_module
        self.simple_sums = {
            dfn.name for dfn in asdl_module.dfns
            if hasattr(dfn.value, "types") and self.is_simple(dfn.value)
        }

    @staticmethod
    def is_simple(sum_type) -> bool:
        return all(not t.fields for t in sum_type.types)

    def java_name(self, asdl_type: str) -> str:
        """Java name of an ASDL type: simple sums get a Type suffix."""
        return asdl_type + "Type" if asdl_type in self.simple_sums else asdl_type

    def java_type(self, field) -> str:
        base = BUILTIN.get(field.type) or self.java_name(field.type)
        if field.seq:
            if base == "int":
                base = "Integer"
            return f"java.util.List<{base}>"
        return base

    def args(self, fields) -> list[tuple[str, str, bool]]:
        """(Java type, name, may be null) for each field, named as asdl_c.py names them."""
        out = []
        unnamed: dict[str, int] = {}
        for f in fields:
            if f.name is None:
                name = f.type
                c = unnamed[name] = unnamed.get(name, 0) + 1
                if c > 1:
                    name = f"name{c - 1}"
            else:
                name = f.name
            out.append((self.java_type(f), name, f.opt or f.seq))
        return out

    # -- files ----------------------------------------------------------------

    def write(self, ast_dir: str, factory_path: str) -> list[str]:
        base_dir = os.path.join(ast_dir, "base")
        os.makedirs(base_dir, exist_ok=True)
        written = []
        for dfn in self.mod.dfns:
            value = dfn.value
            if hasattr(value, "types"):
                if self.is_simple(value):
                    name = self.java_name(dfn.name)
                    written.append(self.write_file(ast_dir, name, self.simple_sum(name, value)))
                else:
                    written.append(self.write_file(base_dir, dfn.name, self.sum_base(dfn.name, value)))
                    for cons in value.types:
                        written.append(self.write_file(
                            ast_dir, cons.name, self.constructor(dfn.name, cons, value.attributes)))
            else:
                written.append(self.write_file(ast_dir, dfn.name, self.product(dfn.name, value)))
        with open(factory_path, "w") as f:
            f.write(self.factory())
        written.append(factory_path)
        return written

    @staticmethod
    def write_file(directory: str, name: str, text: str) -> str:
        path = os.path.join(directory, name + ".java")
        with open(path, "w") as f:
            f.write(text)
        return path

    def simple_sum(self, name, sum_type) -> str:
        values = ", ".join(t.name for t in sum_type.types)
        return (f"{HEADER}package {AST_PACKAGE};\n\n"
                f"public enum {name} {{\n    {values}\n}}\n")

    def fields_block(self, args) -> list[str]:
        return [f"    public {jtype} {name};" for jtype, name, _ in args]

    @staticmethod
    def located(attributes) -> bool:
        """Whether a type's attributes are the source range (Located)."""
        names = [a.name for a in attributes]
        if names and names != LOCATION:
            raise SystemExit(f"unexpected attributes {names}")
        return bool(names)

    @staticmethod
    def location_methods() -> list[str]:
        lines = []
        for name in LOCATION:
            lines += ["", "    @Override", f"    public int {name}() {{", f"        return {name};", "    }"]
        return lines

    def sum_base(self, name, sum_type) -> str:
        located = self.located(sum_type.attributes)
        implements = " implements Located" if located else ""
        lines = [HEADER + f"package {BASE_PACKAGE};", "",
                 f"import {AST_PACKAGE}.AST;",
                 f"import {AST_PACKAGE}.Located;", "",
                 f"public abstract class {name} extends AST{implements} {{", ""]
        lines.append("    public enum Kind {")
        lines.append("        " + ", ".join(t.name for t in sum_type.types))
        lines.append("    }")
        lines.append("")
        attrs = self.args(sum_type.attributes)
        lines += self.fields_block(attrs)
        if attrs:
            lines.append("")
            params = ", ".join(f"{t} {n}" for t, n, _ in attrs)
            lines.append(f"    protected {name}({params}) {{")
            lines += [f"        this.{n} = {n};" for _, n, _ in attrs]
            lines.append("    }")
            lines.append("")
        lines.append("    public abstract Kind kind();")
        if located:
            lines += self.location_methods()
        lines.append("}")
        return "\n".join(lines) + "\n"

    def constructor(self, base, cons, attributes) -> str:
        args = self.args(cons.fields)
        attrs = self.args(attributes)
        lines = [HEADER + f"package {AST_PACKAGE};", "", AST_IMPORTS +
                 f"public final class {cons.name} extends {base} {{", ""]
        lines += self.fields_block(args)
        if args:
            lines.append("")
        params = ", ".join(f"{t} {n}" for t, n, _ in args + attrs)
        lines.append(f"    public {cons.name}({params}) {{")
        if attrs:
            lines.append(f"        super({', '.join(n for _, n, _ in attrs)});")
        lines += [f"        this.{n} = {n};" for _, n, _ in args]
        lines.append("    }")
        lines.append("")
        lines.append("    @Override")
        lines.append("    public Kind kind() {")
        lines.append(f"        return Kind.{cons.name};")
        lines.append("    }")
        lines.append("}")
        return "\n".join(lines) + "\n"

    def product(self, name, product) -> str:
        args = self.args(product.fields)
        attrs = self.args(product.attributes)
        implements = " implements Located" if self.located(product.attributes) else ""
        lines = [HEADER + f"package {AST_PACKAGE};", "", AST_IMPORTS +
                 f"public final class {name} extends AST{implements} {{", ""]
        lines += self.fields_block(args + attrs)
        lines.append("")
        params = ", ".join(f"{t} {n}" for t, n, _ in args + attrs)
        lines.append(f"    public {name}({params}) {{")
        lines += [f"        this.{n} = {n};" for _, n, _ in args + attrs]
        lines.append("    }")
        if implements:
            lines += self.location_methods()
        lines.append("}")
        return "\n".join(lines) + "\n"

    # -- AstFactory -----------------------------------------------------------

    def factory(self) -> str:
        # Single-type imports throughout: an on-demand import of the AST
        # package would make its Module ambiguous with java.lang.Module.
        imports = []
        for dfn in self.mod.dfns:
            value = dfn.value
            if not hasattr(value, "types"):
                imports.append(f"{AST_PACKAGE}.{dfn.name}")
            elif self.is_simple(value):
                imports.append(f"{AST_PACKAGE}.{self.java_name(dfn.name)}")
            else:
                imports.append(f"{BASE_PACKAGE}.{dfn.name}")
                imports += [f"{AST_PACKAGE}.{c.name}" for c in value.types]
        lines = [HEADER + "package org.python.pegen;", ""]
        lines += [f"import {name};" for name in sorted(imports)]
        lines += [f"import {AST_PACKAGE}.AstValueError;", ""]
        lines += [
            "/**",
            " * The _PyAST_* node constructors of CPython's Python/Python-ast.c, under their C",
            " * names and signatures, and the values of the simple sums under their bare C",
            " * names (Load, Add, ...), as grammar actions use them. A missing required",
            " * field throws AstValueError, which Parser.runParser reports as the",
            " * ValueError C would raise.",
            " */",
            "public final class AstFactory {",
            "",
            "    private AstFactory() {}",
            "",
        ]
        for dfn in self.mod.dfns:
            if hasattr(dfn.value, "types") and self.is_simple(dfn.value):
                name = self.java_name(dfn.name)
                for t in dfn.value.types:
                    lines.append(f"    public static final {name} {t.name} = {name}.{t.name};")
        lines.append("")
        for dfn in self.mod.dfns:
            value = dfn.value
            if hasattr(value, "types"):
                if not self.is_simple(value):
                    for cons in value.types:
                        lines += self.factory_function(cons.name, dfn.name, cons.fields, value.attributes)
            else:
                lines += self.factory_function(dfn.name, dfn.name, value.fields, value.attributes)
        lines.append("}")
        return "\n".join(lines) + "\n"

    def factory_function(self, name, rtype, fields, attributes) -> list[str]:
        args = self.args(fields)
        attrs = self.args(attributes)
        params = ", ".join([f"{t} {n}" for t, n, _ in args + attrs] + ["Object arena"])
        lines = [f"    public static {rtype} _PyAST_{name}({params}) {{"]
        for jtype, argname, opt in args:
            if not opt and jtype != "int":
                lines.append(f"        if ({argname} == null) {{")
                lines.append(f'            throw new AstValueError("field \'{argname}\' is required for {name}");')
                lines.append("        }")
        lines.append(f"        return new {name}({', '.join(n for _, n, _ in args + attrs)});")
        lines.append("    }")
        lines.append("")
        return lines


def generate(cpython: str, ast_dir: str, factory_path: str) -> list[str]:
    import sys
    sys.path.insert(0, os.path.join(cpython, "Parser"))
    import asdl
    mod = asdl.parse(os.path.join(cpython, "Parser", "Python.asdl"))
    if not asdl.check(mod):
        raise SystemExit("Python.asdl failed asdl.check()")
    return AsdlJavaGenerator(mod).write(ast_dir, factory_path)
