"""Generate the Unicode tables the Java tokenizer needs from CPython itself.

Usage (from the Jython checkout, with the CPython build the parser follows):
    ../cpython/python build-tools/python/pegen/generate_unicode.py [--output-dir DIR]

Writes UnicodeTables.java into org/python/pegen/lexer/ under
compiler/build/generated/sources/pegen/java/main: the code point
ranges of CPython's _PyUnicode_IsXidStart, _PyUnicode_IsXidContinue and
_PyUnicode_IsPrintable (Objects/unicodectype.c), read through str methods of
the running interpreter, so the tables follow its Unicode version rather than
the JVM's. Must run on the Python version the parser targets.

With --names-dir, also writes unicode_names.txt there: every name C's
_getcode finds in the packed name DAWG of Modules/unicodename_db.h (read from
the source tree of the running interpreter), with its code point after
_check_alias_and_seq(..., with_named_seq=0): aliases resolved, named sequences
left out. The derived names (Hangul syllables, "CJK UNIFIED IDEOGRAPH-XXXX",
...) aren't in the DAWG; UnicodeNames computes them as C does. Each entry is
checked against unicodedata.lookup.
"""

import argparse
import os
import re
import sys
import sysconfig

HERE = os.path.dirname(os.path.abspath(__file__))
JYTHON_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
LEXER_DIR = os.path.join(JYTHON_ROOT, "compiler", "build", "generated", "sources", "pegen",
                   "java", "main", "org", "python", "pegen", "lexer")
TARGET = (3, 15)


def is_xid_start(c):
    # str.isidentifier() is _PyUnicode_ScanIdentifier, which also lets '_' start.
    return c != "_" and c.isidentifier()


def is_xid_continue(c):
    return ("a" + c).isidentifier()


def is_printable(c):
    return c.isprintable()


def ranges(predicate):
    """[start, end] pairs (inclusive) of the code points where predicate holds."""
    out = []
    start = None
    for cp in range(sys.maxunicode + 2):
        hit = cp <= sys.maxunicode and not 0xD800 <= cp <= 0xDFFF and predicate(chr(cp))
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    return out


def write_table(out, name, c_name, table):
    out.write(f"    /** Ranges (first, last, ...) where {c_name} is true. */\n")
    out.write(f"    private static final int[] {name} = {{\n")
    for i in range(0, len(table), 4):
        row = table[i:i + 4]
        out.write("        " + " ".join(f"0x{a:04X}, 0x{b:04X}," for a, b in row) + "\n")
    out.write("    };\n\n")


def c_array(source, name):
    """The values of the C array `name` in source (integer literals)."""
    m = re.search(r"\b" + name + r"\[\] = \{(.*?)\};", source, re.S)
    if m is None:
        sys.exit(f"generate_unicode.py: no array {name} in unicodename_db.h")
    return [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", m.group(1))]


def c_constant(source, name):
    m = re.search(r"\b" + name + r" = (0x[0-9a-fA-F]+|\d+);", source)
    if m is None:
        sys.exit(f"generate_unicode.py: no constant {name} in unicodename_db.h")
    return int(m.group(1), 0)


def dawg_names():
    """(name, code point) for each name in unicodename_db.h's DAWG that
    capi_getcode(..., with_named_seq=0) accepts, aliases resolved."""
    srcdir = sysconfig.get_config_var("srcdir")
    sys.path.insert(0, os.path.join(srcdir, "Tools", "unicode"))
    import dawg
    with open(os.path.join(srcdir, "Modules", "unicodename_db.h")) as f:
        source = f.read()
    packed = bytes(c_array(source, "packed_name_dawg"))
    pos_to_codepoint = c_array(source, "dawg_pos_to_codepoint")
    name_aliases = c_array(source, "name_aliases")
    aliases_start = c_constant(source, "aliases_start")
    aliases_end = c_constant(source, "aliases_end")
    named_sequences_start = c_constant(source, "named_sequences_start")
    named_sequences_end = c_constant(source, "named_sequences_end")
    out = []
    for pos, code in enumerate(pos_to_codepoint):
        name = dawg._inverse_lookup(packed, pos).decode("ascii")
        if named_sequences_start <= code < named_sequences_end:
            continue
        if aliases_start <= code < aliases_end:
            code = name_aliases[code - aliases_start]
        out.append((name, code))
    return out


def write_names(path, names):
    import unicodedata
    for name, code in names:
        if unicodedata.lookup(name) != chr(code):
            sys.exit(f"generate_unicode.py: {name} is U+{code:04X} in the DAWG "
                     f"but not to unicodedata.lookup")
    with open(path, "w", encoding="ascii", newline="\n") as out:
        out.write("# Generated by build-tools/python/pegen/generate_unicode.py from "
                  f"CPython {sys.version.split()[0]} (Unicode {unicodedata.unidata_version})\n")
        out.write("# The character names of \\N{...}: code point (hex) and name.\n")
        for name, code in names:
            out.write(f"{code:X} {name}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--output-dir", default=LEXER_DIR)
    ap.add_argument("--names-dir", help="where to write unicode_names.txt")
    args = ap.parse_args()
    if sys.version_info[:2] != TARGET:
        sys.exit(f"generate_unicode.py: needs Python {TARGET[0]}.{TARGET[1]}, "
                 f"not {sys.version.split()[0]}")

    import unicodedata
    tables = [
        ("XID_START", "_PyUnicode_IsXidStart", ranges(is_xid_start)),
        ("XID_CONTINUE", "_PyUnicode_IsXidContinue", ranges(is_xid_continue)),
        ("PRINTABLE", "_PyUnicode_IsPrintable", ranges(is_printable)),
    ]
    os.makedirs(args.output_dir, exist_ok=True)
    path = os.path.join(args.output_dir, "UnicodeTables.java")
    with open(path, "w") as out:
        out.write("// @generated by build-tools/python/pegen/generate_unicode.py from CPython "
                  f"{sys.version.split()[0]} (Unicode {unicodedata.unidata_version})\n")
        out.write("// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate_unicode.py\n")
        out.write("package org.python.pegen.lexer;\n\n")
        out.write("/**\n")
        out.write(" * The character properties of Objects/unicodectype.c the tokenizer uses,\n")
        out.write(" * as CPython's Unicode database defines them.\n")
        out.write(" */\n")
        out.write("public final class UnicodeTables {\n")
        out.write("    private UnicodeTables() {}\n\n")
        out.write(f'    public static final String UNIDATA_VERSION = "{unicodedata.unidata_version}";\n\n')
        for name, c_name, table in tables:
            write_table(out, name, c_name, table)
        for name, c_name, _ in tables:
            out.write(f"    /** C: {c_name}. */\n")
            out.write(f"    public static boolean {c_name}(int ch) {{\n")
            out.write(f"        return in({name}, ch);\n")
            out.write("    }\n\n")
        out.write("    private static boolean in(int[] table, int ch) {\n")
        out.write("        int lo = 0, hi = table.length / 2 - 1;\n")
        out.write("        while (lo <= hi) {\n")
        out.write("            int mid = (lo + hi) >>> 1;\n")
        out.write("            if (ch < table[2 * mid]) {\n")
        out.write("                hi = mid - 1;\n")
        out.write("            } else if (ch > table[2 * mid + 1]) {\n")
        out.write("                lo = mid + 1;\n")
        out.write("            } else {\n")
        out.write("                return true;\n")
        out.write("            }\n")
        out.write("        }\n")
        out.write("        return false;\n")
        out.write("    }\n")
        out.write("}\n")
    print(f"wrote {path} (" + ", ".join(f"{name} {len(t)} ranges" for name, _, t in tables) + ")")
    if args.names_dir:
        names = dawg_names()
        os.makedirs(args.names_dir, exist_ok=True)
        names_path = os.path.join(args.names_dir, "unicode_names.txt")
        write_names(names_path, names)
        print(f"wrote {names_path} ({len(names)} names)")


if __name__ == "__main__":
    main()
