// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen;

import org.python.pegen.ast.AnnAssign;
import org.python.pegen.ast.Assert;
import org.python.pegen.ast.Assign;
import org.python.pegen.ast.AsyncFor;
import org.python.pegen.ast.AsyncFunctionDef;
import org.python.pegen.ast.AsyncWith;
import org.python.pegen.ast.Attribute;
import org.python.pegen.ast.AugAssign;
import org.python.pegen.ast.Await;
import org.python.pegen.ast.BinOp;
import org.python.pegen.ast.BoolOp;
import org.python.pegen.ast.Break;
import org.python.pegen.ast.Call;
import org.python.pegen.ast.ClassDef;
import org.python.pegen.ast.Compare;
import org.python.pegen.ast.Constant;
import org.python.pegen.ast.Continue;
import org.python.pegen.ast.Delete;
import org.python.pegen.ast.Dict;
import org.python.pegen.ast.DictComp;
import org.python.pegen.ast.ExceptHandler;
import org.python.pegen.ast.Expr;
import org.python.pegen.ast.Expression;
import org.python.pegen.ast.For;
import org.python.pegen.ast.FormattedValue;
import org.python.pegen.ast.FunctionDef;
import org.python.pegen.ast.FunctionType;
import org.python.pegen.ast.GeneratorExp;
import org.python.pegen.ast.Global;
import org.python.pegen.ast.If;
import org.python.pegen.ast.IfExp;
import org.python.pegen.ast.Import;
import org.python.pegen.ast.ImportFrom;
import org.python.pegen.ast.Interactive;
import org.python.pegen.ast.Interpolation;
import org.python.pegen.ast.JoinedStr;
import org.python.pegen.ast.Lambda;
import org.python.pegen.ast.List;
import org.python.pegen.ast.ListComp;
import org.python.pegen.ast.Match;
import org.python.pegen.ast.MatchAs;
import org.python.pegen.ast.MatchClass;
import org.python.pegen.ast.MatchMapping;
import org.python.pegen.ast.MatchOr;
import org.python.pegen.ast.MatchSequence;
import org.python.pegen.ast.MatchSingleton;
import org.python.pegen.ast.MatchStar;
import org.python.pegen.ast.MatchValue;
import org.python.pegen.ast.Module;
import org.python.pegen.ast.Name;
import org.python.pegen.ast.NamedExpr;
import org.python.pegen.ast.Nonlocal;
import org.python.pegen.ast.ParamSpec;
import org.python.pegen.ast.Pass;
import org.python.pegen.ast.Raise;
import org.python.pegen.ast.Return;
import org.python.pegen.ast.Set;
import org.python.pegen.ast.SetComp;
import org.python.pegen.ast.Slice;
import org.python.pegen.ast.Starred;
import org.python.pegen.ast.Subscript;
import org.python.pegen.ast.TemplateStr;
import org.python.pegen.ast.Try;
import org.python.pegen.ast.TryStar;
import org.python.pegen.ast.Tuple;
import org.python.pegen.ast.TypeAlias;
import org.python.pegen.ast.TypeIgnore;
import org.python.pegen.ast.TypeVar;
import org.python.pegen.ast.TypeVarTuple;
import org.python.pegen.ast.UnaryOp;
import org.python.pegen.ast.While;
import org.python.pegen.ast.With;
import org.python.pegen.ast.Yield;
import org.python.pegen.ast.YieldFrom;
import org.python.pegen.ast.alias;
import org.python.pegen.ast.arg;
import org.python.pegen.ast.arguments;
import org.python.pegen.ast.base.excepthandler;
import org.python.pegen.ast.base.expr;
import org.python.pegen.ast.base.mod;
import org.python.pegen.ast.base.pattern;
import org.python.pegen.ast.base.stmt;
import org.python.pegen.ast.base.type_ignore;
import org.python.pegen.ast.base.type_param;
import org.python.pegen.ast.boolopType;
import org.python.pegen.ast.cmpopType;
import org.python.pegen.ast.comprehension;
import org.python.pegen.ast.expr_contextType;
import org.python.pegen.ast.keyword;
import org.python.pegen.ast.match_case;
import org.python.pegen.ast.operatorType;
import org.python.pegen.ast.unaryopType;
import org.python.pegen.ast.withitem;
import org.python.pegen.ast.AstValueError;

/**
 * The _PyAST_* node constructors of CPython's Python/Python-ast.c, under their C
 * names and signatures, and the values of the simple sums under their bare C
 * names (Load, Add, ...), as grammar actions use them. A missing required
 * field throws AstValueError, which Parser.runParser reports as the
 * ValueError C would raise.
 */
public final class AstFactory {

    private AstFactory() {}

    public static final expr_contextType Load = expr_contextType.Load;
    public static final expr_contextType Store = expr_contextType.Store;
    public static final expr_contextType Del = expr_contextType.Del;
    public static final boolopType And = boolopType.And;
    public static final boolopType Or = boolopType.Or;
    public static final operatorType Add = operatorType.Add;
    public static final operatorType Sub = operatorType.Sub;
    public static final operatorType Mult = operatorType.Mult;
    public static final operatorType MatMult = operatorType.MatMult;
    public static final operatorType Div = operatorType.Div;
    public static final operatorType Mod = operatorType.Mod;
    public static final operatorType Pow = operatorType.Pow;
    public static final operatorType LShift = operatorType.LShift;
    public static final operatorType RShift = operatorType.RShift;
    public static final operatorType BitOr = operatorType.BitOr;
    public static final operatorType BitXor = operatorType.BitXor;
    public static final operatorType BitAnd = operatorType.BitAnd;
    public static final operatorType FloorDiv = operatorType.FloorDiv;
    public static final unaryopType Invert = unaryopType.Invert;
    public static final unaryopType Not = unaryopType.Not;
    public static final unaryopType UAdd = unaryopType.UAdd;
    public static final unaryopType USub = unaryopType.USub;
    public static final cmpopType Eq = cmpopType.Eq;
    public static final cmpopType NotEq = cmpopType.NotEq;
    public static final cmpopType Lt = cmpopType.Lt;
    public static final cmpopType LtE = cmpopType.LtE;
    public static final cmpopType Gt = cmpopType.Gt;
    public static final cmpopType GtE = cmpopType.GtE;
    public static final cmpopType Is = cmpopType.Is;
    public static final cmpopType IsNot = cmpopType.IsNot;
    public static final cmpopType In = cmpopType.In;
    public static final cmpopType NotIn = cmpopType.NotIn;

    public static mod _PyAST_Module(java.util.List<stmt> body, java.util.List<type_ignore> type_ignores, Object arena) {
        return new Module(body, type_ignores);
    }

    public static mod _PyAST_Interactive(java.util.List<stmt> body, Object arena) {
        return new Interactive(body);
    }

    public static mod _PyAST_Expression(expr body, Object arena) {
        if (body == null) {
            throw new AstValueError("field 'body' is required for Expression");
        }
        return new Expression(body);
    }

    public static mod _PyAST_FunctionType(java.util.List<expr> argtypes, expr returns, Object arena) {
        if (returns == null) {
            throw new AstValueError("field 'returns' is required for FunctionType");
        }
        return new FunctionType(argtypes, returns);
    }

    public static stmt _PyAST_FunctionDef(String name, arguments args, java.util.List<stmt> body, java.util.List<expr> decorator_list, expr returns, String type_comment, java.util.List<type_param> type_params, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for FunctionDef");
        }
        if (args == null) {
            throw new AstValueError("field 'args' is required for FunctionDef");
        }
        return new FunctionDef(name, args, body, decorator_list, returns, type_comment, type_params, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_AsyncFunctionDef(String name, arguments args, java.util.List<stmt> body, java.util.List<expr> decorator_list, expr returns, String type_comment, java.util.List<type_param> type_params, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for AsyncFunctionDef");
        }
        if (args == null) {
            throw new AstValueError("field 'args' is required for AsyncFunctionDef");
        }
        return new AsyncFunctionDef(name, args, body, decorator_list, returns, type_comment, type_params, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_ClassDef(String name, java.util.List<expr> bases, java.util.List<keyword> keywords, java.util.List<stmt> body, java.util.List<expr> decorator_list, java.util.List<type_param> type_params, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for ClassDef");
        }
        return new ClassDef(name, bases, keywords, body, decorator_list, type_params, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Return(expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Return(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Delete(java.util.List<expr> targets, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Delete(targets, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Assign(java.util.List<expr> targets, expr value, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Assign");
        }
        return new Assign(targets, value, type_comment, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_TypeAlias(expr name, java.util.List<type_param> type_params, expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for TypeAlias");
        }
        if (value == null) {
            throw new AstValueError("field 'value' is required for TypeAlias");
        }
        return new TypeAlias(name, type_params, value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_AugAssign(expr target, operatorType op, expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (target == null) {
            throw new AstValueError("field 'target' is required for AugAssign");
        }
        if (op == null) {
            throw new AstValueError("field 'op' is required for AugAssign");
        }
        if (value == null) {
            throw new AstValueError("field 'value' is required for AugAssign");
        }
        return new AugAssign(target, op, value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_AnnAssign(expr target, expr annotation, expr value, int simple, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (target == null) {
            throw new AstValueError("field 'target' is required for AnnAssign");
        }
        if (annotation == null) {
            throw new AstValueError("field 'annotation' is required for AnnAssign");
        }
        return new AnnAssign(target, annotation, value, simple, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_For(expr target, expr iter, java.util.List<stmt> body, java.util.List<stmt> orelse, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (target == null) {
            throw new AstValueError("field 'target' is required for For");
        }
        if (iter == null) {
            throw new AstValueError("field 'iter' is required for For");
        }
        return new For(target, iter, body, orelse, type_comment, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_AsyncFor(expr target, expr iter, java.util.List<stmt> body, java.util.List<stmt> orelse, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (target == null) {
            throw new AstValueError("field 'target' is required for AsyncFor");
        }
        if (iter == null) {
            throw new AstValueError("field 'iter' is required for AsyncFor");
        }
        return new AsyncFor(target, iter, body, orelse, type_comment, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_While(expr test, java.util.List<stmt> body, java.util.List<stmt> orelse, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (test == null) {
            throw new AstValueError("field 'test' is required for While");
        }
        return new While(test, body, orelse, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_If(expr test, java.util.List<stmt> body, java.util.List<stmt> orelse, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (test == null) {
            throw new AstValueError("field 'test' is required for If");
        }
        return new If(test, body, orelse, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_With(java.util.List<withitem> items, java.util.List<stmt> body, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new With(items, body, type_comment, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_AsyncWith(java.util.List<withitem> items, java.util.List<stmt> body, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new AsyncWith(items, body, type_comment, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Match(expr subject, java.util.List<match_case> cases, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (subject == null) {
            throw new AstValueError("field 'subject' is required for Match");
        }
        return new Match(subject, cases, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Raise(expr exc, expr cause, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Raise(exc, cause, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Try(java.util.List<stmt> body, java.util.List<excepthandler> handlers, java.util.List<stmt> orelse, java.util.List<stmt> finalbody, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Try(body, handlers, orelse, finalbody, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_TryStar(java.util.List<stmt> body, java.util.List<excepthandler> handlers, java.util.List<stmt> orelse, java.util.List<stmt> finalbody, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new TryStar(body, handlers, orelse, finalbody, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Assert(expr test, expr msg, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (test == null) {
            throw new AstValueError("field 'test' is required for Assert");
        }
        return new Assert(test, msg, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Import(java.util.List<alias> names, int is_lazy, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Import(names, is_lazy, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_ImportFrom(String module, java.util.List<alias> names, int level, int is_lazy, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new ImportFrom(module, names, level, is_lazy, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Global(java.util.List<String> names, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Global(names, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Nonlocal(java.util.List<String> names, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Nonlocal(names, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Expr(expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Expr");
        }
        return new Expr(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Pass(int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Pass(lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Break(int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Break(lineno, col_offset, end_lineno, end_col_offset);
    }

    public static stmt _PyAST_Continue(int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Continue(lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_BoolOp(boolopType op, java.util.List<expr> values, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (op == null) {
            throw new AstValueError("field 'op' is required for BoolOp");
        }
        return new BoolOp(op, values, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_NamedExpr(expr target, expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (target == null) {
            throw new AstValueError("field 'target' is required for NamedExpr");
        }
        if (value == null) {
            throw new AstValueError("field 'value' is required for NamedExpr");
        }
        return new NamedExpr(target, value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_BinOp(expr left, operatorType op, expr right, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (left == null) {
            throw new AstValueError("field 'left' is required for BinOp");
        }
        if (op == null) {
            throw new AstValueError("field 'op' is required for BinOp");
        }
        if (right == null) {
            throw new AstValueError("field 'right' is required for BinOp");
        }
        return new BinOp(left, op, right, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_UnaryOp(unaryopType op, expr operand, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (op == null) {
            throw new AstValueError("field 'op' is required for UnaryOp");
        }
        if (operand == null) {
            throw new AstValueError("field 'operand' is required for UnaryOp");
        }
        return new UnaryOp(op, operand, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Lambda(arguments args, expr body, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (args == null) {
            throw new AstValueError("field 'args' is required for Lambda");
        }
        if (body == null) {
            throw new AstValueError("field 'body' is required for Lambda");
        }
        return new Lambda(args, body, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_IfExp(expr test, expr body, expr orelse, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (test == null) {
            throw new AstValueError("field 'test' is required for IfExp");
        }
        if (body == null) {
            throw new AstValueError("field 'body' is required for IfExp");
        }
        if (orelse == null) {
            throw new AstValueError("field 'orelse' is required for IfExp");
        }
        return new IfExp(test, body, orelse, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Dict(java.util.List<expr> keys, java.util.List<expr> values, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Dict(keys, values, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Set(java.util.List<expr> elts, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Set(elts, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_ListComp(expr elt, java.util.List<comprehension> generators, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (elt == null) {
            throw new AstValueError("field 'elt' is required for ListComp");
        }
        return new ListComp(elt, generators, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_SetComp(expr elt, java.util.List<comprehension> generators, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (elt == null) {
            throw new AstValueError("field 'elt' is required for SetComp");
        }
        return new SetComp(elt, generators, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_DictComp(expr key, expr value, java.util.List<comprehension> generators, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (key == null) {
            throw new AstValueError("field 'key' is required for DictComp");
        }
        return new DictComp(key, value, generators, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_GeneratorExp(expr elt, java.util.List<comprehension> generators, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (elt == null) {
            throw new AstValueError("field 'elt' is required for GeneratorExp");
        }
        return new GeneratorExp(elt, generators, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Await(expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Await");
        }
        return new Await(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Yield(expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Yield(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_YieldFrom(expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for YieldFrom");
        }
        return new YieldFrom(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Compare(expr left, java.util.List<cmpopType> ops, java.util.List<expr> comparators, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (left == null) {
            throw new AstValueError("field 'left' is required for Compare");
        }
        return new Compare(left, ops, comparators, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Call(expr func, java.util.List<expr> args, java.util.List<keyword> keywords, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (func == null) {
            throw new AstValueError("field 'func' is required for Call");
        }
        return new Call(func, args, keywords, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_FormattedValue(expr value, int conversion, expr format_spec, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for FormattedValue");
        }
        return new FormattedValue(value, conversion, format_spec, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Interpolation(expr value, Object str, int conversion, expr format_spec, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Interpolation");
        }
        if (str == null) {
            throw new AstValueError("field 'str' is required for Interpolation");
        }
        return new Interpolation(value, str, conversion, format_spec, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_JoinedStr(java.util.List<expr> values, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new JoinedStr(values, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_TemplateStr(java.util.List<expr> values, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new TemplateStr(values, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Constant(Object value, String kind, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Constant");
        }
        return new Constant(value, kind, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Attribute(expr value, String attr, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Attribute");
        }
        if (attr == null) {
            throw new AstValueError("field 'attr' is required for Attribute");
        }
        if (ctx == null) {
            throw new AstValueError("field 'ctx' is required for Attribute");
        }
        return new Attribute(value, attr, ctx, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Subscript(expr value, expr slice, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Subscript");
        }
        if (slice == null) {
            throw new AstValueError("field 'slice' is required for Subscript");
        }
        if (ctx == null) {
            throw new AstValueError("field 'ctx' is required for Subscript");
        }
        return new Subscript(value, slice, ctx, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Starred(expr value, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for Starred");
        }
        if (ctx == null) {
            throw new AstValueError("field 'ctx' is required for Starred");
        }
        return new Starred(value, ctx, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Name(String id, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (id == null) {
            throw new AstValueError("field 'id' is required for Name");
        }
        if (ctx == null) {
            throw new AstValueError("field 'ctx' is required for Name");
        }
        return new Name(id, ctx, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_List(java.util.List<expr> elts, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (ctx == null) {
            throw new AstValueError("field 'ctx' is required for List");
        }
        return new List(elts, ctx, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Tuple(java.util.List<expr> elts, expr_contextType ctx, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (ctx == null) {
            throw new AstValueError("field 'ctx' is required for Tuple");
        }
        return new Tuple(elts, ctx, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static expr _PyAST_Slice(expr lower, expr upper, expr step, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new Slice(lower, upper, step, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static comprehension _PyAST_comprehension(expr target, expr iter, java.util.List<expr> ifs, int is_async, Object arena) {
        if (target == null) {
            throw new AstValueError("field 'target' is required for comprehension");
        }
        if (iter == null) {
            throw new AstValueError("field 'iter' is required for comprehension");
        }
        return new comprehension(target, iter, ifs, is_async);
    }

    public static excepthandler _PyAST_ExceptHandler(expr type, String name, java.util.List<stmt> body, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new ExceptHandler(type, name, body, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static arguments _PyAST_arguments(java.util.List<arg> posonlyargs, java.util.List<arg> args, arg vararg, java.util.List<arg> kwonlyargs, java.util.List<expr> kw_defaults, arg kwarg, java.util.List<expr> defaults, Object arena) {
        return new arguments(posonlyargs, args, vararg, kwonlyargs, kw_defaults, kwarg, defaults);
    }

    public static arg _PyAST_arg(String arg, expr annotation, String type_comment, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (arg == null) {
            throw new AstValueError("field 'arg' is required for arg");
        }
        return new arg(arg, annotation, type_comment, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static keyword _PyAST_keyword(String arg, expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for keyword");
        }
        return new keyword(arg, value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static alias _PyAST_alias(String name, String asname, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for alias");
        }
        return new alias(name, asname, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static withitem _PyAST_withitem(expr context_expr, expr optional_vars, Object arena) {
        if (context_expr == null) {
            throw new AstValueError("field 'context_expr' is required for withitem");
        }
        return new withitem(context_expr, optional_vars);
    }

    public static match_case _PyAST_match_case(pattern pattern, expr guard, java.util.List<stmt> body, Object arena) {
        if (pattern == null) {
            throw new AstValueError("field 'pattern' is required for match_case");
        }
        return new match_case(pattern, guard, body);
    }

    public static pattern _PyAST_MatchValue(expr value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for MatchValue");
        }
        return new MatchValue(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchSingleton(Object value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (value == null) {
            throw new AstValueError("field 'value' is required for MatchSingleton");
        }
        return new MatchSingleton(value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchSequence(java.util.List<pattern> patterns, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new MatchSequence(patterns, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchMapping(java.util.List<expr> keys, java.util.List<pattern> patterns, String rest, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new MatchMapping(keys, patterns, rest, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchClass(expr cls, java.util.List<pattern> patterns, java.util.List<String> kwd_attrs, java.util.List<pattern> kwd_patterns, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (cls == null) {
            throw new AstValueError("field 'cls' is required for MatchClass");
        }
        return new MatchClass(cls, patterns, kwd_attrs, kwd_patterns, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchStar(String name, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new MatchStar(name, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchAs(pattern pattern, String name, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new MatchAs(pattern, name, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static pattern _PyAST_MatchOr(java.util.List<pattern> patterns, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        return new MatchOr(patterns, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static type_ignore _PyAST_TypeIgnore(int lineno, String tag, Object arena) {
        if (tag == null) {
            throw new AstValueError("field 'tag' is required for TypeIgnore");
        }
        return new TypeIgnore(lineno, tag);
    }

    public static type_param _PyAST_TypeVar(String name, expr bound, expr default_value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for TypeVar");
        }
        return new TypeVar(name, bound, default_value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static type_param _PyAST_ParamSpec(String name, expr default_value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for ParamSpec");
        }
        return new ParamSpec(name, default_value, lineno, col_offset, end_lineno, end_col_offset);
    }

    public static type_param _PyAST_TypeVarTuple(String name, expr default_value, int lineno, int col_offset, int end_lineno, int end_col_offset, Object arena) {
        if (name == null) {
            throw new AstValueError("field 'name' is required for TypeVarTuple");
        }
        return new TypeVarTuple(name, default_value, lineno, col_offset, end_lineno, end_col_offset);
    }

}
