// @generated by pegen (generate.py) from Grammar/Tokens
// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py
package org.python.pegen;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public final class TokenTypes {
    private TokenTypes() {}

    public static final int ENDMARKER = 0;
    public static final int NAME = 1;
    public static final int NUMBER = 2;
    public static final int STRING = 3;
    public static final int NEWLINE = 4;
    public static final int INDENT = 5;
    public static final int DEDENT = 6;
    public static final int LPAR = 7;
    public static final int RPAR = 8;
    public static final int LSQB = 9;
    public static final int RSQB = 10;
    public static final int COLON = 11;
    public static final int COMMA = 12;
    public static final int SEMI = 13;
    public static final int PLUS = 14;
    public static final int MINUS = 15;
    public static final int STAR = 16;
    public static final int SLASH = 17;
    public static final int VBAR = 18;
    public static final int AMPER = 19;
    public static final int LESS = 20;
    public static final int GREATER = 21;
    public static final int EQUAL = 22;
    public static final int DOT = 23;
    public static final int PERCENT = 24;
    public static final int LBRACE = 25;
    public static final int RBRACE = 26;
    public static final int EQEQUAL = 27;
    public static final int NOTEQUAL = 28;
    public static final int LESSEQUAL = 29;
    public static final int GREATEREQUAL = 30;
    public static final int TILDE = 31;
    public static final int CIRCUMFLEX = 32;
    public static final int LEFTSHIFT = 33;
    public static final int RIGHTSHIFT = 34;
    public static final int DOUBLESTAR = 35;
    public static final int PLUSEQUAL = 36;
    public static final int MINEQUAL = 37;
    public static final int STAREQUAL = 38;
    public static final int SLASHEQUAL = 39;
    public static final int PERCENTEQUAL = 40;
    public static final int AMPEREQUAL = 41;
    public static final int VBAREQUAL = 42;
    public static final int CIRCUMFLEXEQUAL = 43;
    public static final int LEFTSHIFTEQUAL = 44;
    public static final int RIGHTSHIFTEQUAL = 45;
    public static final int DOUBLESTAREQUAL = 46;
    public static final int DOUBLESLASH = 47;
    public static final int DOUBLESLASHEQUAL = 48;
    public static final int AT = 49;
    public static final int ATEQUAL = 50;
    public static final int RARROW = 51;
    public static final int ELLIPSIS = 52;
    public static final int COLONEQUAL = 53;
    public static final int EXCLAMATION = 54;
    public static final int OP = 55;
    public static final int TYPE_IGNORE = 56;
    public static final int TYPE_COMMENT = 57;
    public static final int SOFT_KEYWORD = 58;
    public static final int FSTRING_START = 59;
    public static final int FSTRING_MIDDLE = 60;
    public static final int FSTRING_END = 61;
    public static final int TSTRING_START = 62;
    public static final int TSTRING_MIDDLE = 63;
    public static final int TSTRING_END = 64;
    public static final int COMMENT = 65;
    public static final int NL = 66;
    public static final int ERRORTOKEN = 67;
    public static final int ENCODING = 68;
    public static final int N_TOKENS = 69;

    public static final String[] NAMES = {
        "ENDMARKER",
        "NAME",
        "NUMBER",
        "STRING",
        "NEWLINE",
        "INDENT",
        "DEDENT",
        "LPAR",
        "RPAR",
        "LSQB",
        "RSQB",
        "COLON",
        "COMMA",
        "SEMI",
        "PLUS",
        "MINUS",
        "STAR",
        "SLASH",
        "VBAR",
        "AMPER",
        "LESS",
        "GREATER",
        "EQUAL",
        "DOT",
        "PERCENT",
        "LBRACE",
        "RBRACE",
        "EQEQUAL",
        "NOTEQUAL",
        "LESSEQUAL",
        "GREATEREQUAL",
        "TILDE",
        "CIRCUMFLEX",
        "LEFTSHIFT",
        "RIGHTSHIFT",
        "DOUBLESTAR",
        "PLUSEQUAL",
        "MINEQUAL",
        "STAREQUAL",
        "SLASHEQUAL",
        "PERCENTEQUAL",
        "AMPEREQUAL",
        "VBAREQUAL",
        "CIRCUMFLEXEQUAL",
        "LEFTSHIFTEQUAL",
        "RIGHTSHIFTEQUAL",
        "DOUBLESTAREQUAL",
        "DOUBLESLASH",
        "DOUBLESLASHEQUAL",
        "AT",
        "ATEQUAL",
        "RARROW",
        "ELLIPSIS",
        "COLONEQUAL",
        "EXCLAMATION",
        "OP",
        "TYPE_IGNORE",
        "TYPE_COMMENT",
        "SOFT_KEYWORD",
        "FSTRING_START",
        "FSTRING_MIDDLE",
        "FSTRING_END",
        "TSTRING_START",
        "TSTRING_MIDDLE",
        "TSTRING_END",
        "COMMENT",
        "NL",
        "ERRORTOKEN",
        "ENCODING",
    };

    /** Operator and delimiter strings mapped to their token type. */
    public static final Map<String, Integer> EXACT_TOKENS;
    static {
        Map<String, Integer> m = new HashMap<>();
        m.put("(", LPAR);
        m.put(")", RPAR);
        m.put("[", LSQB);
        m.put("]", RSQB);
        m.put(":", COLON);
        m.put(",", COMMA);
        m.put(";", SEMI);
        m.put("+", PLUS);
        m.put("-", MINUS);
        m.put("*", STAR);
        m.put("/", SLASH);
        m.put("|", VBAR);
        m.put("&", AMPER);
        m.put("<", LESS);
        m.put(">", GREATER);
        m.put("=", EQUAL);
        m.put(".", DOT);
        m.put("%", PERCENT);
        m.put("{", LBRACE);
        m.put("}", RBRACE);
        m.put("==", EQEQUAL);
        m.put("!=", NOTEQUAL);
        m.put("<=", LESSEQUAL);
        m.put(">=", GREATEREQUAL);
        m.put("~", TILDE);
        m.put("^", CIRCUMFLEX);
        m.put("<<", LEFTSHIFT);
        m.put(">>", RIGHTSHIFT);
        m.put("**", DOUBLESTAR);
        m.put("+=", PLUSEQUAL);
        m.put("-=", MINEQUAL);
        m.put("*=", STAREQUAL);
        m.put("/=", SLASHEQUAL);
        m.put("%=", PERCENTEQUAL);
        m.put("&=", AMPEREQUAL);
        m.put("|=", VBAREQUAL);
        m.put("^=", CIRCUMFLEXEQUAL);
        m.put("<<=", LEFTSHIFTEQUAL);
        m.put(">>=", RIGHTSHIFTEQUAL);
        m.put("**=", DOUBLESTAREQUAL);
        m.put("//", DOUBLESLASH);
        m.put("//=", DOUBLESLASHEQUAL);
        m.put("@", AT);
        m.put("@=", ATEQUAL);
        m.put("->", RARROW);
        m.put("...", ELLIPSIS);
        m.put(":=", COLONEQUAL);
        m.put("!", EXCLAMATION);
        EXACT_TOKENS = Collections.unmodifiableMap(m);
    }

    /** Parser/token.c _PyToken_OneChar. */
    public static int _PyToken_OneChar(int c1) {
        switch (c1) {
        case '!': return EXCLAMATION;
        case '%': return PERCENT;
        case '&': return AMPER;
        case '(': return LPAR;
        case ')': return RPAR;
        case '*': return STAR;
        case '+': return PLUS;
        case ',': return COMMA;
        case '-': return MINUS;
        case '.': return DOT;
        case '/': return SLASH;
        case ':': return COLON;
        case ';': return SEMI;
        case '<': return LESS;
        case '=': return EQUAL;
        case '>': return GREATER;
        case '@': return AT;
        case '[': return LSQB;
        case ']': return RSQB;
        case '^': return CIRCUMFLEX;
        case '{': return LBRACE;
        case '|': return VBAR;
        case '}': return RBRACE;
        case '~': return TILDE;
        }
        return OP;
    }

    /** Parser/token.c _PyToken_TwoChars. */
    public static int _PyToken_TwoChars(int c1, int c2) {
        switch (c1) {
        case '!':
            switch (c2) {
            case '=': return NOTEQUAL;
            }
            break;
        case '%':
            switch (c2) {
            case '=': return PERCENTEQUAL;
            }
            break;
        case '&':
            switch (c2) {
            case '=': return AMPEREQUAL;
            }
            break;
        case '*':
            switch (c2) {
            case '*': return DOUBLESTAR;
            case '=': return STAREQUAL;
            }
            break;
        case '+':
            switch (c2) {
            case '=': return PLUSEQUAL;
            }
            break;
        case '-':
            switch (c2) {
            case '=': return MINEQUAL;
            case '>': return RARROW;
            }
            break;
        case '/':
            switch (c2) {
            case '/': return DOUBLESLASH;
            case '=': return SLASHEQUAL;
            }
            break;
        case ':':
            switch (c2) {
            case '=': return COLONEQUAL;
            }
            break;
        case '<':
            switch (c2) {
            case '<': return LEFTSHIFT;
            case '=': return LESSEQUAL;
            case '>': return NOTEQUAL;
            }
            break;
        case '=':
            switch (c2) {
            case '=': return EQEQUAL;
            }
            break;
        case '>':
            switch (c2) {
            case '=': return GREATEREQUAL;
            case '>': return RIGHTSHIFT;
            }
            break;
        case '@':
            switch (c2) {
            case '=': return ATEQUAL;
            }
            break;
        case '^':
            switch (c2) {
            case '=': return CIRCUMFLEXEQUAL;
            }
            break;
        case '|':
            switch (c2) {
            case '=': return VBAREQUAL;
            }
            break;
        }
        return OP;
    }

    /** Parser/token.c _PyToken_ThreeChars. */
    public static int _PyToken_ThreeChars(int c1, int c2, int c3) {
        switch (c1) {
        case '*':
            switch (c2) {
            case '*':
                switch (c3) {
                case '=': return DOUBLESTAREQUAL;
                }
                break;
            }
            break;
        case '.':
            switch (c2) {
            case '.':
                switch (c3) {
                case '.': return ELLIPSIS;
                }
                break;
            }
            break;
        case '/':
            switch (c2) {
            case '/':
                switch (c3) {
                case '=': return DOUBLESLASHEQUAL;
                }
                break;
            }
            break;
        case '<':
            switch (c2) {
            case '<':
                switch (c3) {
                case '=': return LEFTSHIFTEQUAL;
                }
                break;
            }
            break;
        case '>':
            switch (c2) {
            case '>':
                switch (c3) {
                case '=': return RIGHTSHIFTEQUAL;
                }
                break;
            }
            break;
        }
        return OP;
    }
}
