"""Generate the opcode tables the Java compiler needs from CPython itself.

Usage (from the Jython checkout, with the CPython build the compiler follows):
    ../cpython/python src/pegen/tools/generate_opcodes.py [--output-dir DIR]

Writes Opcode.java into src/org/python/pegen/compile/: the opcode numbers of
opcode.opmap (pseudo-instructions included), the per-opcode flags of
pycore_opcode_metadata.h that _opcode exposes (OPCODE_HAS_ARG, _CONST, _NAME,
_JUMP, _FREE, _LOCAL, IS_PSEUDO's exception-handler flag), the NB_* operand
kinds of BINARY_OP, the CALL_INTRINSIC_1/2 operands, and the SPECIAL_*
operands of LOAD_SPECIAL. Must run on the Python version the compiler
targets.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
JYTHON_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
COMPILE_DIR = os.path.join(JYTHON_ROOT, "src", "org", "python", "pegen", "compile")
TARGET = (3, 15)

FLAGS = [
    ("HAS_ARG", "has_arg"),
    ("HAS_CONST", "has_const"),
    ("HAS_NAME", "has_name"),
    ("HAS_JUMP", "has_jump"),
    ("HAS_FREE", "has_free"),
    ("HAS_LOCAL", "has_local"),
    ("HAS_EXC", "has_exc"),
]


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--output-dir", default=COMPILE_DIR)
    args = ap.parse_args()
    if sys.version_info[:2] != TARGET:
        sys.exit(f"generate_opcodes.py: needs Python {TARGET[0]}.{TARGET[1]}, "
                 f"not {sys.version.split()[0]}")

    import _opcode
    import opcode

    opmap = opcode.opmap
    size = max(opmap.values()) + 1
    out = []
    w = out.append
    w(f"// @generated by src/pegen/tools/generate_opcodes.py from CPython "
      f"{sys.version.split()[0]}\n")
    w("// DO NOT EDIT. Regenerate with src/pegen/tools/generate_opcodes.py\n")
    w("package org.python.pegen.compile;\n\n")
    w("/**\n")
    w(" * CPython's opcodes (Include/opcode_ids.h, pseudo-instructions included) and\n")
    w(" * the parts of pycore_opcode_metadata.h, pycore_intrinsics.h and\n")
    w(" * pycore_ceval.h the compiler uses.\n")
    w(" */\n")
    w("public final class Opcode {\n")
    w("    private Opcode() {}\n\n")
    for name, value in sorted(opmap.items(), key=lambda kv: (kv[1], kv[0])):
        w(f"    public static final int {name} = {value};\n")
    w(f"\n    /** One past the largest opcode. */\n")
    w(f"    public static final int MAX_OPCODE_PLUS_ONE = {size};\n\n")

    names = [None] * size
    for name, value in opmap.items():
        names[value] = name
    w("    /** Opcode names, by opcode (null where there is none). */\n")
    w("    public static final String[] OPNAME = {\n")
    for n in names:
        w(f'        {"null" if n is None else chr(34) + n + chr(34)},\n')
    w("    };\n\n")

    for i, (flag, _) in enumerate(FLAGS):
        w(f"    private static final int {flag}_FLAG = {1 << i};\n")
    w("\n    private static final int[] FLAGS = new int[MAX_OPCODE_PLUS_ONE];\n")
    w("    static {\n")
    for value in range(size):
        if names[value] is None:
            continue
        bits = [f"{flag}_FLAG" for flag, fn in FLAGS if getattr(_opcode, fn)(value)]
        if bits:
            w(f"        FLAGS[{names[value]}] = {' | '.join(bits)};\n")
    w("    }\n\n")
    for flag, _ in FLAGS:
        w(f"    /** C: OPCODE_{flag}(op). */\n")
        w(f"    public static boolean OPCODE_{flag}(int op) {{\n")
        w(f"        return (FLAGS[op] & {flag}_FLAG) != 0;\n")
        w("    }\n\n")

    w("    /* BINARY_OP operands (Include/internal/pycore_code.h NB_*) */\n")
    for i, (name, _) in enumerate(_opcode.get_nb_ops()):
        w(f"    public static final int {name} = {i};\n")
    w("\n    /* CALL_INTRINSIC_1 operands (Include/internal/pycore_intrinsics.h) */\n")
    for i, name in enumerate(_opcode.get_intrinsic1_descs()):
        w(f"    public static final int {name} = {i};\n")
    w("\n    /* CALL_INTRINSIC_2 operands */\n")
    for i, name in enumerate(_opcode.get_intrinsic2_descs()):
        w(f"    public static final int {name} = {i};\n")
    w("\n    /* LOAD_SPECIAL operands (Include/internal/pycore_ceval.h SPECIAL_*) */\n")
    for i, name in enumerate(_opcode.get_special_method_names()):
        w(f"    public static final int SPECIAL_{name.upper()} = {i};\n")
    w("}\n")

    os.makedirs(args.output_dir, exist_ok=True)
    path = os.path.join(args.output_dir, "Opcode.java")
    with open(path, "w") as f:
        f.write("".join(out))
    print(f"wrote {path} ({len(opmap)} opcodes)")


if __name__ == "__main__":
    main()
