"""Generate the Java PEG parser from CPython's grammar.

Usage (from the Jython checkout):
    python3 src/pegen/tools/generate.py [--cpython ../cpython] [--skip-actions]

Writes GeneratedParser.java and TokenTypes.java into src/org/python/pegen/,
and the AST classes and AstFactory generated from Parser/Python.asdl.
Grammar actions are translated by default, so the parser builds the AST;
--skip-actions emits a recognizer instead (dummy results, no AST).
Requires Python >= 3.10 and a CPython checkout, whose Tools/peg_generator
supplies pegen.
"""

import argparse
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
JYTHON_ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
PEGEN_DIR = os.path.join(JYTHON_ROOT, "src", "org", "python", "pegen")

# Java replacement for python.gram's C @trailer (_PyPegen_parse).
PYTHON_GRAM_TRAILER = """
public Object parse() {
    try {
        if (p.start_rule == Parser.FILE_INPUT) {
            return file_rule();
        } else if (p.start_rule == Parser.SINGLE_INPUT) {
            return interactive_rule();
        } else if (p.start_rule == Parser.EVAL_INPUT) {
            return eval_rule();
        } else if (p.start_rule == Parser.FUNC_TYPE_INPUT) {
            return func_type_rule();
        }
        return null;
    } catch (StackOverflowError e) {
        // TODO(stack depth): see Parser.MAXSTACK.
        p.stackOverflow();
        return null;
    }
}
"""


def generate_token_types(all_tokens, exact_tokens, package, out):
    out.write("// @generated by pegen (generate.py) from Grammar/Tokens\n")
    out.write("// DO NOT EDIT. Regenerate with src/pegen/tools/generate.py\n")
    out.write(f"package {package};\n\n")
    out.write("import java.util.Collections;\n")
    out.write("import java.util.HashMap;\n")
    out.write("import java.util.Map;\n\n")
    out.write("public final class TokenTypes {\n")
    out.write("    private TokenTypes() {}\n\n")
    for index, name in sorted(all_tokens.items()):
        out.write(f"    public static final int {name} = {index};\n")
    out.write(f"    public static final int N_TOKENS = {len(all_tokens)};\n\n")
    out.write("    public static final String[] NAMES = {\n")
    for _, name in sorted(all_tokens.items()):
        out.write(f'        "{name}",\n')
    out.write("    };\n\n")
    out.write("    /** Operator and delimiter strings mapped to their token type. */\n")
    out.write("    public static final Map<String, Integer> EXACT_TOKENS;\n")
    out.write("    static {\n")
    out.write("        Map<String, Integer> m = new HashMap<>();\n")
    for op, index in sorted(exact_tokens.items(), key=lambda kv: kv[1]):
        out.write(f'        m.put("{op}", {all_tokens[index]});\n')
    out.write("        EXACT_TOKENS = Collections.unmodifiableMap(m);\n")
    out.write("    }\n")
    out.write("}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--cpython", default=os.path.join(JYTHON_ROOT, "..", "cpython"))
    ap.add_argument("--grammar", help="default: <cpython>/Grammar/python.gram")
    ap.add_argument("--tokens", help="default: <cpython>/Grammar/Tokens")
    ap.add_argument("--output-dir", default=PEGEN_DIR)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--skip-actions", dest="skip_actions", action="store_true",
                      help="emit dummy results instead of grammar actions "
                           "(a recognizer)")
    mode.add_argument("--actions", dest="skip_actions", action="store_false",
                      help="translate the grammar actions (the default)")
    ap.set_defaults(skip_actions=False)
    args = ap.parse_args()

    cpython = os.path.abspath(args.cpython)
    sys.path.insert(0, os.path.join(cpython, "Tools", "peg_generator"))
    sys.path.insert(0, HERE)
    from pegen.build import build_parser, generate_token_definitions
    import asdl_java
    from action_overrides import OVERRIDES
    from java_generator import JavaParserGenerator

    grammar_file = args.grammar or os.path.join(cpython, "Grammar", "python.gram")
    tokens_file = args.tokens or os.path.join(cpython, "Grammar", "Tokens")

    grammar, _, _ = build_parser(grammar_file)
    with open(tokens_file) as f:
        all_tokens, exact_tokens, non_exact_tokens = generate_token_definitions(f)

    parser_java = io.StringIO()
    gen = JavaParserGenerator(
        grammar,
        all_tokens,
        exact_tokens,
        non_exact_tokens,
        parser_java,
        skip_actions=args.skip_actions,
        trailer=PYTHON_GRAM_TRAILER if "file" in grammar.rules else None,
        overrides=None if args.skip_actions else OVERRIDES,
    )
    gen.generate(grammar_file)
    problems = gen.action_problems()
    if problems:
        # Untranslated actions: extend action_translator.py or add an entry
        # to action_overrides.py.  Nothing is written.
        for problem in problems:
            print(problem, file=sys.stderr)
        print(f"{len(problems)} action problem(s); no files written", file=sys.stderr)
        sys.exit(1)

    os.makedirs(args.output_dir, exist_ok=True)
    parser_path = os.path.join(args.output_dir, "GeneratedParser.java")
    with open(parser_path, "w") as out:
        out.write(parser_java.getvalue())

    tokens_path = os.path.join(args.output_dir, "TokenTypes.java")
    with open(tokens_path, "w") as out:
        generate_token_types(all_tokens, exact_tokens, "org.python.pegen", out)

    ast_files = asdl_java.generate(
        cpython,
        os.path.join(args.output_dir, "ast"),
        os.path.join(args.output_dir, "AstFactory.java"),
    )

    print(f"wrote {parser_path} ({len(gen.all_rules)} rules, {len(gen.keywords)} keywords)")
    print(f"wrote {tokens_path} ({len(all_tokens)} tokens)")
    print(f"wrote {len(ast_files)} AST files from Parser/Python.asdl")


if __name__ == "__main__":
    main()
