// @generated by asdl_java.py from Parser/Python.asdl
// DO NOT EDIT. Regenerate with build-tools/python/pegen/generate.py
package org.python.pegen.ast.base;

import org.python.pegen.ast.AST;
import org.python.pegen.ast.Located;

public abstract class stmt extends AST implements Located {

    public enum Kind {
        FunctionDef, AsyncFunctionDef, ClassDef, Return, Delete, Assign, TypeAlias, AugAssign, AnnAssign, For, AsyncFor, While, If, With, AsyncWith, Match, Raise, Try, TryStar, Assert, Import, ImportFrom, Global, Nonlocal, Expr, Pass, Break, Continue
    }

    public int lineno;
    public int col_offset;
    public int end_lineno;
    public int end_col_offset;

    protected stmt(int lineno, int col_offset, int end_lineno, int end_col_offset) {
        this.lineno = lineno;
        this.col_offset = col_offset;
        this.end_lineno = end_lineno;
        this.end_col_offset = end_col_offset;
    }

    public abstract Kind kind();

    @Override
    public int lineno() {
        return lineno;
    }

    @Override
    public int col_offset() {
        return col_offset;
    }

    @Override
    public int end_lineno() {
        return end_lineno;
    }

    @Override
    public int end_col_offset() {
        return end_col_offset;
    }
}
